word_E907A:     dc.w $5079,$0A00,$00E8  ; DATA XREF: update_ent_6D+22   o ROM:stru_E953C   o ...
                dc.w $5879,$0A00,$0000
                dc.w $4079,$0A00,$E8E8
                dc.w $C879,$0A00,$E800
word_E9092:     dc.w $5082, $A00,  $E8  ; DATA XREF: ROM:stru_E953C   o ROM:stru_E9560   o ...
                dc.w $4082, $A00,$E8E8
                dc.w $5882, $A00,    0
                dc.w $C882, $A00,$E800
word_E90AA:     dc.w $C88B, $F00,$F0F0  ; DATA XREF: ROM:stru_E953C   o ROM:stru_E9560   o ...
word_E90B0:     dc.w $C89B, $F00,$F0F0  ; DATA XREF: ROM:stru_E953C   o ROM:stru_E9560   o ...
word_E90B6:     dc.w $C8AB, $F00,$F0F0  ; DATA XREF: ROM:stru_E953C   o ROM:stru_E9560   o ...
word_E90BC:     dc.w $C8BB, $F00,$F0F0  ; DATA XREF: ROM:stru_E953C   o ROM:stru_E9560   o ...
word_E90C2:     dc.w $C800, $A00,$F4F4  ; DATA XREF: sub_589E8+2E   o ROM:stru_E953C   o ...
word_E90C8:     dc.w $C8CB, $F00,$F0F0  ; DATA XREF: ROM:stru_E953C   o ROM:stru_E9560   o ...
word_E90CE:     dc.w $C8EC, $F00,$F0F0  ; DATA XREF: ROM:stru_E95DC   o ROM:stru_E9604   o
word_E90D4:     dc.w $C8FC, $100,$F8FC  ; DATA XREF: ROM:off_2B6C4   o ROM:stru_E9774   o ...
word_E90DA:     dc.w $C8FE, $400,$FCF8  ; DATA XREF: ROM:off_2B6C4   o ROM:stru_E9774   o ...
word_E90E0:     dc.w $C900, $500,$F8F8  ; DATA XREF: ROM:off_2B6C4   o ROM:stru_E9774   o ...
word_E90E6:     dc.w $C100, $500,$F8F8  ; DATA XREF: ROM:off_2B6C4   o ROM:stru_E9774   o ...
word_E90EC:     dc.w $C86C,    0,$FCFC  ; DATA XREF: ROM:stru_E97E0   o
word_E90F2:     dc.w $C86D, $500,$F8F8  ; DATA XREF: ROM:stru_E97D4   o
word_E90F8:     dc.w $C871,    0,$FCFC  ; DATA XREF: ROM:stru_E97E0   o
word_E90FE:     dc.w $4873,    0,$FCFC  ; DATA XREF: ROM:stru_E979C   o
                dc.w $50DB,    0,  $F8
                dc.w $58DB,    0,    0
                dc.w $40DB,    0,$F8F8
                dc.w $C8DB,    0,$F800
word_E911C:     dc.w $4840, $500,$F8F8  ; DATA XREF: ROM:stru_E979C   o
                dc.w $50DB,    0,  $F8
                dc.w $58DB,    0,    0
                dc.w $40DB,    0,$F8F8
                dc.w $C8DB,    0,$F800
word_E913A:     dc.w $50DB,    0,  $F8  ; DATA XREF: ROM:stru_E979C   o
                dc.w $58DB,    0,    0
                dc.w $40DB,    0,$F8F8
                dc.w $C8DB,    0,$F800
word_E9152:     dc.w $50DC,    0,  $F8  ; DATA XREF: ROM:stru_E97B8   o
                dc.w $58DC,    0,    0
                dc.w $40DC,    0,$F8F8
                dc.w $C8DC,    0,$F800
word_E916A:     dc.w $4856, $A00,$F4F4  ; DATA XREF: ROM:stru_E979C   o
                dc.w $50DB,    0,  $F8
                dc.w $58DB,    0,    0
                dc.w $40DB,    0,$F8F8
                dc.w $C8DB,    0,$F800
word_E9188:     dc.w $C82C, $500,$F8F8  ; DATA XREF: ROM:stru_E95A4   o ROM:stru_E95C0   o ...
word_E918E:     dc.w $C830, $500,$F8F8  ; DATA XREF: ROM:stru_E95A4   o ROM:stru_E95C0   o
word_E9194:     dc.w $C834, $500,$F8F8  ; DATA XREF: ROM:stru_E95A4   o ROM:stru_E95C0   o
word_E919A:     dc.w $C838, $500,$F8F8  ; DATA XREF: ROM:stru_E95A4   o ROM:stru_E95C0   o
word_E91A0:     dc.w $C868, $500,$F8F8  ; DATA XREF: ROM:stru_E95A4   o ROM:stru_E95C0   o
word_E91A6:     dc.w $C809, $A00,$F4F4  ; DATA XREF: ROM:stru_E95DC   o ROM:stru_E9604   o
word_E91AC:     dc.w $C812, $A00,$F4F4  ; DATA XREF: ROM:stru_E95DC   o ROM:stru_E9604   o
word_E91B2:     dc.w $C81B, $A00,$F4F4  ; DATA XREF: ROM:stru_E95DC   o ROM:stru_E9604   o
word_E91B8:     dc.w $C824, $500,$F8F8  ; DATA XREF: ROM:stru_E95DC   o ROM:stru_E9604   o
word_E91BE:     dc.w $C828, $500,$F8F8  ; DATA XREF: ROM:stru_E95DC   o ROM:stru_E9604   o
word_E91C4:     dc.w $C83C, $500,$F8F8  ; DATA XREF: ROM:stru_E962C   o ROM:stru_E964C   o ...
word_E91CA:     dc.w $C840, $500,$F8F8  ; DATA XREF: ROM:stru_E962C   o ROM:stru_E964C   o ...
word_E91D0:     dc.w $C873,    0,$FCFC  ; DATA XREF: ROM:stru_E9638   o ROM:stru_E964C   o
word_E91D6:     dc.w $C872,    0,$FCFC  ; DATA XREF: ROM:stru_E9638   o ROM:stru_E964C   o
                dc.w $4856, $A00,$F4F4
                dc.w $50DB,    0,  $F8
                dc.w $58DB,    0,    0
                dc.w $40DB,    0,$F8F8
                dc.w $C8DB,    0,$F800
word_E91FA:     dc.w $C874,    0,$FCFC  ; DATA XREF: sub_2F2A4+1E   o sub_4019A+36   o ...
word_E9200:     dc.w $C875,    0,$FCFC  ; DATA XREF: ROM:stru_E9660   o ROM:stru_E966C   o
word_E9206:     dc.w $C856, $A00,$F4F4  ; DATA XREF: ROM:stru_E9680   o ROM:stru_E968C   o ...
word_E920C:     dc.w $C85F, $A00,$F4F4  ; DATA XREF: ROM:stru_E9680   o ROM:stru_E968C   o ...
word_E9212:     dc.w $C844, $500,$F8F8  ; DATA XREF: ROM:stru_E96AC   o ROM:stru_E96C8   o ...
word_E9218:     dc.w $C871,    0,$FCFC  ; DATA XREF: ROM:stru_E96AC   o ROM:stru_E96C8   o ...
word_E921E:     dc.w $C876,    0,$FCFC  ; DATA XREF: ROM:stru_E96E0   o ROM:stru_E96F0   o ...
word_E9224:     dc.w $C877,    0,$FCFC  ; DATA XREF: ROM:stru_E96E0   o ROM:stru_E9738   o
word_E922A:     dc.w $4873,    0,$FCFC  ; DATA XREF: ROM:stru_E97B8   o
                dc.w $50DC,    0,  $F8
                dc.w $58DC,    0,    0
                dc.w $40DC,    0,$F8F8
                dc.w $C8DC,    0,$F800
word_E9248:     dc.w $4840, $500,$F8F8  ; DATA XREF: ROM:stru_E97B8   o
                dc.w $50DC,    0,  $F8
                dc.w $58DC,    0,    0
                dc.w $40DC,    0,$F8F8
                dc.w $C8DC,    0,$F800
word_E9266:     dc.w $4856, $A00,$F4F4  ; DATA XREF: ROM:stru_E97B8   o
                dc.w $50DC,    0,  $F8
                dc.w $58DC,    0,    0
                dc.w $40DC,    0,$F8F8
                dc.w $C8DC,    0,$F800
word_E9284:     dc.w $48E3, $A00,$FEFE  ; DATA XREF: ROM:stru_E97EC   o
                dc.w $D0E3, $A00,$EAEA
word_E9290:     dc.w $40E0, $800,$FCE8  ; DATA XREF: ROM:stru_E97EC   o
                dc.w $C8E0, $800,$FC00
word_E929C:     dc.w $58DD, $200,$E8FC  ; DATA XREF: ROM:stru_E97EC   o
                dc.w $C8DD, $200,  $FC
                dc.w $48E3, $A00,$EAEC
                dc.w $50E3, $A00,$D6D8
                dc.w $48E3, $A00,$1214
                dc.w $D0E3, $A00,$FE00
                dc.w $40E0, $800,$FCD0
                dc.w $48E0, $800,$FCE8
                dc.w $40E0, $800,$FC00
                dc.w $C8E0, $800,$FC18
                dc.w $58DD, $200,  $FC
                dc.w $48DD, $200,$18FC
                dc.w $58DD, $200,$D0FC
                dc.w $C8DD, $200,$E8FC
word_E92F0:     dc.w $4809, $A00,$F409  ; DATA XREF: ROM:stru_E9818   o
                dc.w $4812, $A00,$F4F9
                dc.w $481B, $A00,$F4EE
                dc.w $4824, $500,$F8E7
                dc.w $C828, $500,$F8DD
word_E930E:     dc.w $5809, $A00,$F409  ; DATA XREF: ROM:stru_E9818   o
                dc.w $5812, $A00,$F4F9
                dc.w $581B, $A00,$F4ED
                dc.w $5824, $500,$F8E6
                dc.w $D828, $500,$F8DD
word_E932C:     dc.w $5009, $A00,$F40A  ; DATA XREF: ROM:stru_E9818   o
                dc.w $5012, $A00,$F4FA
                dc.w $501B, $A00,$F4ED
                dc.w $5024, $500,$F8E6
                dc.w $D028, $500,$F8DC
word_E934A:     dc.w $4009, $A00,$F40A  ; DATA XREF: ROM:stru_E9818   o
                dc.w $4012, $A00,$F4FA
                dc.w $401B, $A00,$F4EE
                dc.w $4024, $500,$F8E7
                dc.w $C028, $500,$F8DC
word_E9368:     dc.w $48CB, $F00,$F0F0  ; DATA XREF: ROM:stru_E982C   o ROM:stru_E9850   o
                dc.w $488B, $F00,  $F0
                dc.w $488B, $F00,$E0F0
                dc.w $488B, $F00,$F000
                dc.w $C88B, $F00,$F0E0
word_E9386:     dc.w $488B, $F00,$F0F0  ; DATA XREF: ROM:stru_E982C   o ROM:stru_E9850   o
                dc.w $588B, $F00,$DCF0
                dc.w $408B, $F00,$F0DC
                dc.w $488B, $F00,$F004
                dc.w $488B, $F00, $5F0
                dc.w $489B, $F00,  $E0
                dc.w $409B, $F00,    0
                dc.w $589B, $F00,$E0E0
                dc.w $D09B, $F00,$E000
word_E93BC:     dc.w $488B, $F00,$F0F0  ; DATA XREF: ROM:stru_E982C   o ROM:stru_E9850   o
                dc.w $409B, $F00,$F0D8
                dc.w $589B, $F00,$D8F0
                dc.w $489B, $F00,$F008
                dc.w $489B, $F00, $8F0
                dc.w $489B, $F00, $3DD
                dc.w $409B, $F00, $303
                dc.w $509B, $F00,$DD03
                dc.w $D89B, $F00,$DDDD
word_E93F2:     dc.w $C84C, $500,$F8F8  ; DATA XREF: ROM:stru_E96FC   o ROM:stru_E9710   o ...
word_E93F8:     dc.w $C850, $500,$F8F8  ; DATA XREF: ROM:stru_E96FC   o ROM:stru_E9710   o ...
word_E93FE:     dc.w $C854,    0,$FCFC  ; DATA XREF: ROM:stru_E96FC   o ROM:stru_E9710   o ...
word_E9404:     dc.w $C855,    0,$FCFC  ; DATA XREF: ROM:stru_E96FC   o ROM:stru_E9710   o ...
word_E940A:     dc.w $489B, $F00,$F0F0  ; DATA XREF: ROM:stru_E982C   o ROM:stru_E9850   o
                dc.w $58AB, $F00,$D6F0
                dc.w $40AB, $F00,$F00A
                dc.w $48AB, $F00, $AF0
                dc.w $48AB, $F00,$F0D6
                dc.w $58AB, $F00,$DB05
                dc.w $40AB, $F00, $5DB
                dc.w $48AB, $F00, $505
                dc.w $D0AB, $F00,$DBDB
word_E9440:     dc.w $48AB, $F00,$F0F0  ; DATA XREF: ROM:stru_E982C   o ROM:stru_E9850   o
                dc.w $40BB, $F00,$F00C
                dc.w $48BB, $F00, $CF0
                dc.w $48BB, $F00,$F0D4
                dc.w $58BB, $F00,$D4F0
                dc.w $48BB, $F00,$DBDB
                dc.w $40BB, $F00,$DB05
                dc.w $58BB, $F00, $5DB
                dc.w $D0BB, $F00, $505
word_E9476:     dc.w $48CB, $F00,$F0F0  ; DATA XREF: ROM:stru_E9870   o
                dc.w $588B, $F00,$E2F0
                dc.w $588B, $F00,$F0E4
                dc.w $D08B, $F00,$F0FC
word_E948E:     dc.w $48CB, $F00,$F0F0  ; DATA XREF: ROM:stru_E9870   o
                dc.w $588B, $F00,$DEF0
                dc.w $588B, $F00,$F0DE
                dc.w $D08B, $F00,$F002
word_E94A6:     dc.w $588B, $F00,$F0F0  ; DATA XREF: ROM:stru_E9870   o
                dc.w $589B, $F00,$F0D9
                dc.w $509B, $F00,$F007
                dc.w $509B, $F00,$DDE3
                dc.w $D89B, $F00,$DDFD
word_E94C4:     dc.w $589B, $F00,$F0F0  ; DATA XREF: ROM:stru_E9870   o
                dc.w $58AB, $F00,$F0D2
                dc.w $50AB, $F00,$F00E
                dc.w $58AB, $F00,$D8E0
                dc.w $D0AB, $F00,$D800
word_E94E2:     dc.w $58AB, $F00,$F0F0  ; DATA XREF: ROM:stru_E9870   o
                dc.w $58BB, $F00,$F00F
                dc.w $50BB, $F00,$F0D1
                dc.w $58BB, $F00,$D5DF
                dc.w $D0BB, $F00,$D501
word_E9500:     dc.w $C878,    0,$FCFC  ; DATA XREF: ROM:stru_E975C   o
word_E9506:     dc.w $4874,    0,$F8F8  ; DATA XREF: ROM:stru_E975C   o
                dc.w $C878,    0,$FCFC
                dc.w $C874,    0,$F8F8
word_E9518:     dc.w $4872,    0,$F8F8  ; DATA XREF: ROM:stru_E975C   o
                dc.w $C878,    0,$FCFC
                dc.w $C872,    0,$F8F8
word_E952A:     dc.w $C8DD, $200,$F4FC  ; DATA XREF: ROM:off_30814   o
word_E9530:     dc.w $C8E0, $800,$FCF4  ; DATA XREF: ROM:off_30814   o
word_E9536:     dc.w $C8E3, $A00,$F4F4  ; DATA XREF: ROM:off_30814   o
stru_E953C:     dc.w word_E90C2-*       ; field_0 ; DATA XREF: update_ent_C3+20   o ROM:off_2255C   o ...
                dc.w     1              ; field_2
                dc.w word_E90C8-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E907A-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9092-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90AA-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_E90B0-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E90B6-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E90BC-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E90BC-*       ; field_0
                dc.w   $FF              ; field_2
stru_E9560:     dc.w word_E90C2-*       ; field_0 ; DATA XREF: sub_17642:loc_17664   o sub_17678:loc_1768C   o ...
                dc.w     1              ; field_2
                dc.w word_E90C8-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E907A-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9092-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90AA-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E90B0-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E90B6-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90BC-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90BC-*       ; field_0
                dc.w   $FF              ; field_2
stru_E9584:     dc.w word_E90C8-*       ; field_0 ; DATA XREF: update_ent_8C+40   o ROM:off_2255C   o ...
                dc.w     1              ; field_2
                dc.w word_E907A-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9092-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90AA-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E90B0-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90B6-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90BC-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90BC-*       ; field_0
                dc.w   $FF              ; field_2
stru_E95A4:     dc.w word_E90C2-*       ; field_0 ; DATA XREF: ROM:off_2255C   o sub_2A5B6+28   o ...
                dc.w     1              ; field_2
                dc.w word_E9188-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E918E-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E9194-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E919A-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E91A0-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E91A0-*       ; field_0
                dc.w   $FF              ; field_2
stru_E95C0:     dc.w word_E90C2-*       ; field_0 ; DATA XREF: update_ent_60+1C   o ROM:off_31E7C   o ...
                dc.w     1              ; field_2
                dc.w word_E9188-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E918E-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9194-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E919A-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E91A0-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E91A0-*       ; field_0
                dc.w   $FF              ; field_2
stru_E95DC:     dc.w word_E90C2-*       ; field_0 ; DATA XREF: ROM:off_2255C   o sub_2A5B6+2   o ...
                dc.w     1              ; field_2
                dc.w word_E90C8-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90CE-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90C2-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E91A6-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E91AC-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E91B2-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E91B8-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E91BE-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E91BE-*       ; field_0
                dc.w   $FF              ; field_2
stru_E9604:     dc.w word_E90C2-*       ; field_0 ; DATA XREF: ROM:0002B52A   o ROM:0002B538   o ...
                dc.w     1              ; field_2
                dc.w word_E90C8-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90CE-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90C2-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E91A6-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E91AC-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E91B2-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E91B8-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E91BE-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E91BE-*       ; field_0
                dc.w   $FF              ; field_2
stru_E962C:     dc.w word_E91C4-*       ; field_0 ; DATA XREF: sub_50C88+A   o ROM:stru_E962C   o ...
                dc.w     1              ; field_2
                dc.w word_E91CA-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E962C-*       ; field_0
                dc.w     0              ; field_2
stru_E9638:     dc.w word_E91D0-*       ; field_0 ; DATA XREF: update_ent_74+16   o ROM:000E9648   o ...
                dc.w     1              ; field_2
                dc.w word_E91FA-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E91D6-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E91FA-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E9638-*       ; field_0
                dc.w 0                  ; field_2
stru_E964C:     dc.w word_E91C4-*       ; field_0 ; DATA XREF: ROM:stru_E964C   o ROM:stru_E964C   o ...
                dc.w     1              ; field_2
                dc.w word_E91D0-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E91CA-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E91D6-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E964C-*       ; field_0
                dc.w     0              ; field_2
stru_E9660:     dc.w word_E91FA-*       ; field_0 ; DATA XREF: ROM:stru_E9660   o ROM:stru_E9660   o ...
                dc.w     1              ; field_2
                dc.w word_E9200-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E9660-*       ; field_0
                dc.w     0              ; field_2
stru_E966C:     dc.w word_E91FA-*       ; field_0 ; DATA XREF: ROM:stru_E966C   o ROM:stru_E966C   o ...
                dc.w     1              ; field_2
                dc.w word_E9200-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E966C-*       ; field_0
                dc.w     0              ; field_2
                dc.w word_E9200-*       ; field_0
                dc.w   $FF              ; field_2
                dc.w word_E91FA-*       ; field_0
                dc.w $FF                ; field_2
stru_E9680:     dc.w word_E9206-*       ; field_0 ; DATA XREF: update_ent_80+16   o sub_2B210+2A   o ...
                dc.w     1              ; field_2
                dc.w word_E920C-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E9680-*       ; field_0
                dc.w     0              ; field_2
stru_E968C:     dc.w word_E9206-*       ; field_0 ; DATA XREF: more_weapon_menu_stuff+54   o sub_30670+10   o ...
                dc.w     2              ; field_2
                dc.w word_E920C-*       ; field_0
                dc.w     2              ; field_2
                dc.w stru_E968C-*       ; field_0
                dc.w     0              ; field_2
stru_E9698:     dc.w word_E9206-*       ; field_0 ; DATA XREF: sub_1808C+D8   o ROM:stru_E9698   o ...
                dc.w     1              ; field_2
                dc.w word_E91CA-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E920C-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E91C4-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E9698-*       ; field_0
                dc.w     0              ; field_2
stru_E96AC:     dc.w word_E9206-*       ; field_0 ; DATA XREF: ROM:stru_E96AC   o ROM:stru_E96AC   o ...
                dc.w     1              ; field_2
                dc.w word_E9188-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E920C-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E96AC-*       ; field_0
                dc.w     0              ; field_2
                dc.w word_E9212-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E9218-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E9218-*       ; field_0
                dc.w   $FF              ; field_2
stru_E96C8:     dc.w word_E9212-*       ; field_0 ; DATA XREF: ROM:stru_E96C8   o ROM:stru_E96C8   o
                dc.w     6              ; field_2
                dc.w word_E9218-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_E9218-*       ; field_0
                dc.w   $FF              ; field_2
stru_E96D4:     dc.w word_E9212-*       ; field_0 ; DATA XREF: ROM:stru_E96D4   o ROM:stru_E96D4   o
                dc.w     1              ; field_2
                dc.w word_E9218-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9218-*       ; field_0
                dc.w   $FF              ; field_2
stru_E96E0:     dc.w word_E9218-*       ; field_0 ; DATA XREF: ROM:0002B52E   o ROM:0002B53C   o ...
                dc.w     2              ; field_2
                dc.w word_E9224-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E921E-*       ; field_0
                dc.w     2              ; field_2
                dc.w stru_E96E0-*       ; field_0
                dc.w     0              ; field_2
stru_E96F0:     dc.w word_E9218-*       ; field_0 ; DATA XREF: ROM:stru_E96F0   o ROM:stru_E96F0   o ...
                dc.w     2              ; field_2
                dc.w word_E921E-*       ; field_0
                dc.w     2              ; field_2
                dc.w stru_E96F0-*       ; field_0
                dc.w     0              ; field_2
stru_E96FC:     dc.w word_E93F2-*       ; field_0 ; DATA XREF: sub_4418E+2E   o sub_441EC+4E   o ...
                dc.w     3              ; field_2
                dc.w word_E93F8-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E93FE-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E9404-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E9404-*       ; field_0
                dc.w   $FF              ; field_2
stru_E9710:     dc.w word_E93F2-*       ; field_0 ; DATA XREF: ROM:off_546DE   o ROM:stru_E9710   o ...
                dc.w     5              ; field_2
                dc.w word_E93F8-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_E93FE-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_E9404-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_E9404-*       ; field_0
                dc.w   $FF              ; field_2
stru_E9724:     dc.w word_E93F2-*       ; field_0 ; DATA XREF: ROM:off_546DE   o ROM:stru_E9724   o ...
                dc.w     1              ; field_2
                dc.w word_E93F8-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E93FE-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9404-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9404-*       ; field_0
                dc.w   $FF              ; field_2
stru_E9738:     dc.w word_E90C2-*       ; field_0 ; DATA XREF: sub_18846+46   o ROM:stru_E9738   o ...
                dc.w     1              ; field_2
                dc.w word_E93F2-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E93F8-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E93FE-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9404-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9404-*       ; field_0
                dc.w   $FF              ; field_2
                dc.w word_E9218-*       ; field_0
                dc.w   $FF              ; field_2
                dc.w word_E9224-*       ; field_0
                dc.w   $FF              ; field_2
                dc.w word_E921E-*       ; field_0
                dc.w   $FF              ; field_2
stru_E975C:     dc.w word_E9500-*       ; field_0 ; DATA XREF: update_ent_12+18   o sub_2B8E0+28   o ...
                dc.w   $20              ; field_2
                dc.w word_E9218-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9506-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9518-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9506-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E975C-*       ; field_0
                dc.w     0              ; field_2
stru_E9774:     dc.w word_E90D4-*       ; field_0 ; DATA XREF: ROM:stru_E9774   o ROM:stru_E9774   o ...
                dc.w     1              ; field_2
                dc.w word_E90E0-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90DA-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90E6-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E9774-*       ; field_0
                dc.w     0              ; field_2
stru_E9788:     dc.w word_E90D4-*       ; field_0 ; DATA XREF: update_ent_52+3E   o update_ent_95+3E   o ...
                dc.w     2              ; field_2
                dc.w word_E90E0-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E90DA-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E90E6-*       ; field_0
                dc.w     2              ; field_2
                dc.w stru_E9788-*       ; field_0
                dc.w     0              ; field_2
stru_E979C:     dc.w word_E913A-*       ; field_0 ; DATA XREF: ROM:stru_E979C   o ROM:stru_E979C   o ...
                dc.w   $18              ; field_2
                dc.w word_E90FE-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E911C-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E916A-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E911C-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90FE-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E979C-*       ; field_0
                dc.w     0              ; field_2
stru_E97B8:     dc.w word_E9152-*       ; field_0 ; DATA XREF: sub_2BAB4+A   o ROM:stru_E97B8   o ...
                dc.w   $18              ; field_2
                dc.w word_E922A-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9248-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9266-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9248-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E922A-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E97B8-*       ; field_0
                dc.w     0              ; field_2
stru_E97D4:     dc.w word_E90F2-*       ; field_0 ; DATA XREF: ROM:off_2BDA8   o ROM:stru_E97D4   o ...
                dc.w     8              ; field_2
                dc.w word_E93F2-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E97D4-*       ; field_0
                dc.w     0              ; field_2
stru_E97E0:     dc.w word_E90EC-*       ; field_0 ; DATA XREF: ROM:off_2BDA8   o ROM:stru_E97E0   o ...
                dc.w     8              ; field_2
                dc.w word_E90F8-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E97E0-*       ; field_0
                dc.w     0              ; field_2
stru_E97EC:     dc.w word_E929C-*       ; field_0 ; DATA XREF: ROM:stru_E97EC   o ROM:stru_E97EC   o ...
                dc.w     1              ; field_2
                dc.w word_E9290-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9284-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9206-*       ; field_0
                dc.w     5              ; field_2
                dc.w stru_E97EC-*       ; field_0
                dc.w     0              ; field_2
stru_E9800:     dc.w word_E9218-*       ; field_0 ; DATA XREF: sub_17386+2C   o ROM:stru_E9800   o ...
                dc.w     1              ; field_2
                dc.w word_E90C2-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90C8-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E907A-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9092-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E90C8-*       ; field_0
                dc.w   $FF              ; field_2
stru_E9818:     dc.w word_E92F0-*       ; field_0 ; DATA XREF: ROM:stru_E9818   o ROM:stru_E9818   o ...
                dc.w     1              ; field_2
                dc.w word_E930E-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E932C-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E934A-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_E9818-*       ; field_0
                dc.w     0              ; field_2
stru_E982C:     dc.w word_E90C8-*       ; field_0 ; DATA XREF: ROM:stru_E982C   o ROM:stru_E982C   o ...
                dc.w     1              ; field_2
                dc.w word_E907A-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9092-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9368-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9386-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E93BC-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E940A-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9440-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9404-*       ; field_0
                dc.w   $FF              ; field_2
stru_E9850:     dc.w word_E9092-*       ; field_0 ; DATA XREF: sub_30A76+1A   o update_ent_11B+120   o ...
                dc.w     1              ; field_2
                dc.w word_E907A-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9368-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9386-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E93BC-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E940A-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9440-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9404-*       ; field_0
                dc.w   $FF              ; field_2
stru_E9870:     dc.w word_E907A-*       ; field_0 ; DATA XREF: sub_2A32A+2A   o ROM:stru_E9870   o ...
                dc.w     1              ; field_2
                dc.w word_E9092-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9476-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E948E-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E94A6-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E94C4-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E94E2-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9404-*       ; field_0
                dc.w   $FF              ; field_2
                dc.w word_E907A-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9092-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9476-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E948E-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E94A6-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E94C4-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E94E2-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9404-*       ; field_0
                dc.w   $FF              ; field_2
word_E98B0:     dc.w  $300, $F00,$F0D0  ; DATA XREF: sub_1CF82+17C   o
                dc.w  $310, $F00,$F0F0
                dc.w $8320, $F00,$F010
word_E98C2:     dc.w  $300, $F00,$D4E4  ; DATA XREF: sub_1D152+92   o
                dc.w  $310, $B00,$D404
                dc.w  $31C, $F00,$F4E4
                dc.w  $32C, $B00,$F404
                dc.w  $338, $E00,$14E4
                dc.w $8344, $A00,$1404
                dc.w $65B4, $F00,$80F0
                dc.w $65B4, $F00,$A0F0
                dc.w $65B4, $F00,$C0F0
                dc.w $65B4, $F00,$E0F0
                dc.w $65B4, $F00,  $F0
                dc.w $65B4, $F00,$20F0
                dc.w $65B4, $F00,$40F0
                dc.w $E5B4, $F00,$60F0
                dc.w $75C4, $500,$F0F0
                dc.w $7DC4, $500,$F000
                dc.w $65C4, $500,  $F0
                dc.w $EDC4, $500,    0
                dc.w $75C8, $500,$F0F0
                dc.w $7DC8, $500,$F000
                dc.w $65C8, $500,  $F0
                dc.w $EDC8, $500,    0
                dc.w $404C, $600,$F2F1
                dc.w $C84C, $600,$F201
word_E9952:     dc.w $4480, $A00,$F4F4  ; DATA XREF: sub_2BBC0:loc_2BBF4   o
                dc.w $47F0, $500,$F8F0
                dc.w $CFF0, $500,$F8FF
word_E9964:     dc.w $47F0, $500,$F8F0  ; DATA XREF: ROM:off_178E6   o
                dc.w $4FF0, $500,$F8FF
                dc.w $C584, $500,$F8F8
word_E9976:     dc.w $47F0, $500,$F8F0  ; DATA XREF: ROM:off_178E6   o
                dc.w $4FF0, $500,$F8FF
                dc.w $C588, $500,$F8F8
word_E9988:     dc.w $47F0, $500,$F8F0  ; DATA XREF: ROM:off_178E6   o
                dc.w $4FF0, $500,$F8FF
                dc.w $C58C, $500,$F8F8
word_E999A:     dc.w $47F0, $500,$F8F0  ; DATA XREF: ROM:off_178E6   o
                dc.w $4FF0, $500,$F8FF
                dc.w $C590, $500,$F8F8
word_E99AC:     dc.w $47F0, $500,$F8F0  ; DATA XREF: ROM:off_178E6   o
                dc.w $4FF0, $500,$F8FF
                dc.w $C594, $500,$F8F8
word_E99BE:     dc.w $47F0, $500,$F8F0  ; DATA XREF: ROM:off_178E6   o
                dc.w $4FF0, $500,$F8FF
                dc.w $C598, $500,$F8F8
                dc.w $68CA, $600, $9F7
                dc.w $68BE, $100,$E911
                dc.w $68B4, $C00, $9F4
                dc.w $68AC, $D00,$F9F7
                dc.w $68A3, $A00,$E1F9
                dc.w $68D2,    0,$19EF
                dc.w $E8D0, $100,$1107
                dc.w $68D4, $600, $8F8
                dc.w $68BE, $100,$E812
                dc.w $68B4, $C00, $8F5
                dc.w $68AC, $D00,$F8F8
                dc.w $68A3, $A00,$E0FA
                dc.w $E8D3,    0,$1008
                dc.w $68DC, $600, $8F8
                dc.w $68BE, $100,$E813
                dc.w $68B4, $C00, $8F6
                dc.w $68AC, $D00,$F8F9
                dc.w $68A3, $A00,$E0FB
                dc.w $68DA, $100,$1008
                dc.w $E8E2,    0,$18F0
                dc.w $68C0, $500,$1006
                dc.w $68C4, $600, $8F6
                dc.w $68BE, $100,$E910
                dc.w $68B4, $C00, $9F3
                dc.w $68AC, $D00,$F9F6
                dc.w $E8A3, $A00,$E1F8
                dc.w $68BC, $100,$E910
                dc.w $68C0, $500,$1006
                dc.w $68C4, $600, $8F6
                dc.w $68B4, $C00, $9F3
                dc.w $68AC, $D00,$F9F6
                dc.w $E8A3, $A00,$E1F8
                dc.w $68B8, $500,$E910
                dc.w $68C0, $500,$1006
                dc.w $68C4, $600, $8F6
                dc.w $68B4, $C00, $9F3
                dc.w $68AC, $D00,$F9F6
                dc.w $E8A3, $A00,$E1F8
                dc.w $680F, $100, $3FB
                dc.w $6000, $600,$F0F0
                dc.w $E800, $600,$F000
                dc.w $6811, $100, $3FC
                dc.w $6000, $600,$F0F0
                dc.w $E800, $600,$F000
                dc.w $6813, $100, $3FB
                dc.w $6000, $600,$F0F0
                dc.w $E800, $600,$F000
                dc.w $680F, $100, $3FB
                dc.w $6006, $A00,$F0E8
                dc.w $E806, $A00,$F000
                dc.w $6006, $A00,$F0E8
                dc.w $6806, $A00,$F000
                dc.w $E811, $100, $3FC
                dc.w $6006, $A00,$F0E8
                dc.w $6806, $A00,$F000
                dc.w $E813, $100, $3FB
                dc.w $6821, $100,$F1F0
                dc.w $6833, $F00, $1DE
                dc.w $6823, $F00, $1FE
                dc.w $6815, $C00,$E9F6
                dc.w $E819, $D00,$F1F8
                dc.w $684E, $600,$F300
                dc.w $604E, $600,$F3F0
                dc.w $6054, $400, $8F0
                dc.w $E854, $400, $800
                dc.w $684E, $600,$F300
                dc.w $604E, $600,$F3F0
                dc.w $6056, $400, $8F0
                dc.w $E856, $400, $800
                dc.w $6861, $600,$EF02
                dc.w $687E, $E00,$ECF2
                dc.w $6867, $D00, $70A
                dc.w $688A, $D00,$F9EE
                dc.w $6858, $A00,$EF12
                dc.w $68A1, $400,$19DE
                dc.w $689E, $800,$11E6
                dc.w $E89A, $C00, $9E6
                dc.w $686F, $700,$EF02
                dc.w $687A, $500, $F02
                dc.w $6877, $800, $712
                dc.w $687E, $E00,$ECF2
                dc.w $688A, $D00,$F9EE
                dc.w $6858, $A00,$EF12
                dc.w $68A1, $400,$19DE
                dc.w $689E, $800,$11E6
                dc.w $E89A, $C00, $9E6
                dc.w $6861, $600,$F4FF
                dc.w $6867, $D00, $C07
                dc.w $6858, $A00,$F40F
                dc.w $687E, $E00,$F1EF
                dc.w $6896, $C00,$19F0
                dc.w $6892, $C00,$11E8
                dc.w $E88A, $D00, $1E8
                dc.w $687A, $500,$13FE
                dc.w $686F, $700,$F4FF
                dc.w $6877, $800, $C0F
                dc.w $6858, $A00,$F40F
                dc.w $687E, $E00,$F1EF
                dc.w $6896, $C00,$19F0
                dc.w $6892, $C00,$11E8
                dc.w $E88A, $D00, $1E8
word_E9C2E:     dc.w $6863, $500,$10EE  ; DATA XREF: ROM:stru_E9E1C   o ROM:stru_E9E40   o ...
                dc.w $6845, $C00, $EF1
                dc.w $6839, $E00,$F6F1
                dc.w $6871, $500,$10FD
                dc.w $E800, $D00,$E6F1
word_E9C4C:     dc.w $6863, $500,$10EE  ; DATA XREF: ROM:stru_E9E1C   o ROM:stru_E9E40   o
                dc.w $6829, $F00,$F8F3
                dc.w $6871, $500,$10FD
                dc.w $E800, $D00,$E8F3
word_E9C64:     dc.w $6863, $500,$10EE  ; DATA XREF: ROM:stru_E9E1C   o ROM:stru_E9E40   o
                dc.w $6819, $F00,$FAF3
                dc.w $6871, $500,$10FD
                dc.w $E800, $D00,$EAF3
word_E9C7C:     dc.w $6808, $D00,$EBF2  ; DATA XREF: ROM:stru_E9E1C   o ROM:stru_E9E40   o
                dc.w $686B,    0,$1CFB
                dc.w $6867, $500,$14EB
                dc.w $6819, $F00,$FBF2
                dc.w $6875,    0,$1C0A
                dc.w $E876, $500,$14FA
word_E9CA0:     dc.w $6808, $D00,$EEF0  ; DATA XREF: ROM:stru_E9E1C   o ROM:stru_E9E40   o
                dc.w $686B,    0,$1CFB
                dc.w $6867, $500,$14EB
                dc.w $6819, $F00,$FEF0
                dc.w $6875,    0,$1C0A
                dc.w $E876, $500,$14FA
word_E9CC4:     dc.w $6808, $D00,$E6F2  ; DATA XREF: ROM:stru_E9E08   o
                dc.w $6863, $500, $DEB
                dc.w $6839, $E00,$F6F2
                dc.w $6845, $C00, $EF2
                dc.w $687A, $800,$18FF
                dc.w $E87D, $400,$10F7
word_E9CE8:     dc.w $6808, $D00,$E4F4  ; DATA XREF: ROM:stru_E9E08   o
                dc.w $6867, $500, $CEE
                dc.w $6829, $F00,$F4F4
                dc.w $686B,    0,$16FC
                dc.w $E871, $500,$10F9
word_E9D06:     dc.w $686F, $400,$10EE  ; DATA XREF: ROM:stru_E9E08   o
                dc.w $686C, $800,$18F6
                dc.w $6819, $F00,$F6EF
                dc.w $6871, $500, $EF0
                dc.w $E800, $D00,$E6EF
word_E9D24:     dc.w $6863, $500,$10EE  ; DATA XREF: ROM:stru_E9E08   o
                dc.w $6829, $F00,$F4F4
                dc.w $6875,    0,$1508
                dc.w $6876, $500, $DF8
                dc.w $E800, $D00,$E4F4
word_E9D42:     dc.w $6800, $D00,$E7F0  ; DATA XREF: ROM:stru_E9E68   o
                dc.w $6857, $E00,$F7F0
                dc.w $6863, $500,$10EE
                dc.w $6845, $C00, $FEF
                dc.w $E871, $500,$10FD
word_E9D60:     dc.w $6808, $D00,$E6F2  ; DATA XREF: ROM:stru_E9E68   o
                dc.w $6857, $E00,$F6F2
                dc.w $6863, $500,$10EE
                dc.w $6845, $C00, $EF1
                dc.w $E871, $500,$10FD
word_E9D7E:     dc.w $6818,    0,$F013  ; DATA XREF: ROM:stru_E9E68   o
                dc.w $6810, $D00,$E7F3
                dc.w $6849, $100,$F613
                dc.w $684B, $E00,$F6F3
                dc.w $6863, $500,$10EE
                dc.w $6845, $C00, $EF3
                dc.w $E871, $500,$10FD
word_E9DA8:     dc.w $6875,    0,$140B  ; DATA XREF: ROM:stru_E9E80   o
                dc.w $6863, $500,$10ED
                dc.w $6845, $C00, $CF1
                dc.w $6876, $500, $CFB
                dc.w $6839, $E00,$F4F1
                dc.w $E808, $D00,$E4F2
word_E9DCC:     dc.w $686B,    0,$14FE  ; DATA XREF: ROM:stru_E9E80   o
                dc.w $6867, $500, $CEE
                dc.w $6808, $D00,$E4F2
                dc.w $6845, $C00, $CF1
                dc.w $6839, $E00,$F4F1
                dc.w $E871, $500,$10FD
word_E9DF0:     dc.w $6863, $500, $CEF  ; DATA XREF: ROM:stru_E9E80   o
                dc.w $6829, $F00,$F4F1
                dc.w $6808, $D00,$E4F2
                dc.w $E871, $500, $CFD
stru_E9E08:     dc.w word_E9CC4-*       ; field_0 ; DATA XREF: ROM:off_2C550   o ROM:stru_E9E08   o ...
                dc.w     4              ; field_2
                dc.w word_E9CE8-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_E9D06-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_E9D24-*       ; field_0
                dc.w     4              ; field_2
                dc.w stru_E9E08-*       ; field_0
                dc.w     0              ; field_2
stru_E9E1C:     dc.w word_E9C2E-*       ; field_0 ; DATA XREF: ROM:off_2C550   o ROM:stru_E9E1C   o ...
                dc.w     6              ; field_2
                dc.w word_E9C4C-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_E9C64-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_E9C7C-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_E9CA0-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_E9C7C-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_E9C64-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_E9C4C-*       ; field_0
                dc.w     5              ; field_2
                dc.w stru_E9E1C-*       ; field_0
                dc.w     0              ; field_2
stru_E9E40:     dc.w word_E9C2E-*       ; field_0 ; DATA XREF: ROM:off_2C550   o ROM:stru_E9E40   o ...
                dc.w     1              ; field_2
                dc.w word_E9C4C-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9C64-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9C7C-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E9CA0-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_E9CA0-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E9C7C-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9C64-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9C4C-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_E9C2E-*       ; field_0
                dc.w   $FF              ; field_2
stru_E9E68:     dc.w word_E9C2E-*       ; field_0 ; DATA XREF: ROM:off_2C550   o ROM:stru_E9E68   o ...
                dc.w     3              ; field_2
                dc.w word_E9D42-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_E9D60-*       ; field_0
                dc.w     8              ; field_2
                dc.w word_E9D7E-*       ; field_0
                dc.w   $10              ; field_2
                dc.w word_E9D60-*       ; field_0
                dc.w     8              ; field_2
                dc.w word_E9D42-*       ; field_0
                dc.w   $FF              ; field_2
stru_E9E80:     dc.w word_E9DA8-*       ; field_0 ; DATA XREF: ROM:off_2C550   o sub_2C622+10   o ...
                dc.w     3              ; field_2
                dc.w word_E9DF0-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9DCC-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E9DF0-*       ; field_0
                dc.w     2              ; field_2
                dc.w stru_E9E80-*       ; field_0
                dc.w     0              ; field_2
word_E9E94:     dc.w $606F, $500, $6E8  ; DATA XREF: ROM:stru_EA00E   o ROM:stru_EA036   o ...
                dc.w $686F, $500, $608
                dc.w $6865, $100,$D2FC
                dc.w $6000, $A00,$E0E8
                dc.w $602D, $F00,$F8E0
                dc.w $605D, $C00,$18E0
                dc.w $685D, $C00,$1800
                dc.w $682D, $F00,$F800
                dc.w $E800, $A00,$E000
word_E9ECA:     dc.w $606B, $500, $8DE  ; DATA XREF: ROM:stru_EA00E   o
                dc.w $686B, $500, $812
                dc.w $6861, $500,$D2F8
                dc.w $605D, $C00,$18E0
                dc.w $685D, $C00,$1800
                dc.w $6009, $A00,$E0E8
                dc.w $603D, $F00,$F8E0
                dc.w $683D, $F00,$F800
                dc.w $E809, $A00,$E000
word_E9F00:     dc.w $685D, $C00,$1800  ; DATA XREF: ROM:stru_EA00E   o
                dc.w $605D, $C00,$18E0
                dc.w $6067, $500, $BDA
                dc.w $6867, $500, $B16
                dc.w $6861, $500,$D4F8
                dc.w $604D, $F00,$F9E0
                dc.w $684D, $F00,$F900
                dc.w $6012, $A00,$E1E8
                dc.w $E812, $A00,$E100
word_E9F36:     dc.w $606F, $500, $4EA  ; DATA XREF: ROM:stru_EA00E   o ROM:stru_EA04A   o
                dc.w $686F, $500, $406
                dc.w $6865, $100,$D1FC
                dc.w $6000, $A00,$E0E8
                dc.w $602D, $F00,$F8E0
                dc.w $605D, $C00,$18E0
                dc.w $685D, $C00,$1800
                dc.w $682D, $F00,$F800
                dc.w $E800, $A00,$E000
word_E9F6C:     dc.w $685D, $C00,$1800  ; DATA XREF: ROM:stru_EA00E   o
                dc.w $605D, $C00,$18E0
                dc.w $6067, $500, $DD8
                dc.w $6867, $500, $D18
                dc.w $6861, $500,$D5F8
                dc.w $604D, $F00,$F9E0
                dc.w $684D, $F00,$F900
                dc.w $6012, $A00,$E1E8
                dc.w $E812, $A00,$E100
word_E9FA2:     dc.w $606F, $500, $4EA  ; DATA XREF: ROM:stru_EA036   o ROM:stru_EA04A   o
                dc.w $686F, $500, $406
                dc.w $603D, $F00,$F8E0
                dc.w $683D, $F00,$F800
                dc.w $6861, $500,$D2F8
                dc.w $601B, $A00,$E0E8
                dc.w $681B, $A00,$E000
                dc.w $605D, $C00,$18E0
                dc.w $E85D, $C00,$1800
word_E9FD8:     dc.w $685D, $C00,$1800  ; DATA XREF: ROM:stru_EA036   o
                dc.w $605D, $C00,$18E0
                dc.w $686F, $500,$FE03
                dc.w $606F, $500,$FEED
                dc.w $602D, $F00,$F9E0
                dc.w $682D, $F00,$F900
                dc.w $6024, $A00,$E1E8
                dc.w $6824, $A00,$E100
                dc.w $E861, $500,$D4F9
stru_EA00E:     dc.w word_E9F36-*       ; field_0 ; DATA XREF: ROM:off_2C984   o ROM:stru_EA00E   o ...
                dc.w     4              ; field_2
                dc.w word_E9E94-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_E9ECA-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_E9F00-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E9F6C-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_E9F00-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E9ECA-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_E9E94-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_E9F36-*       ; field_0
                dc.w     4              ; field_2
                dc.w stru_EA00E-*       ; field_0
                dc.w     0              ; field_2
stru_EA036:     dc.w word_E9E94-*       ; field_0 ; DATA XREF: ROM:off_2C984   o ROM:stru_EA036   o ...
                dc.w     4              ; field_2
                dc.w word_E9FA2-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_E9FD8-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_E9FA2-*       ; field_0
                dc.w     5              ; field_2
                dc.w stru_EA036-*       ; field_0
                dc.w     0              ; field_2
stru_EA04A:     dc.w word_E9E94-*       ; field_0 ; DATA XREF: ROM:off_2C984   o ROM:stru_EA04A   o ...
                dc.w     4              ; field_2
                dc.w word_E9FA2-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_E9F36-*       ; field_0
                dc.w     2              ; field_2
                dc.w stru_EA04A-*       ; field_0
                dc.w     0              ; field_2
word_EA05A:     dc.w $6839, $E00,$EAF3  ; DATA XREF: ROM:stru_EA5DC   o ROM:stru_EA67C   o
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $DFB
                dc.w $6810, $E00,$FCF1
                dc.w $6835, $500,$12FB
                dc.w $6858, $400,$F209
                dc.w $E800, $F00,$DCF1
word_EA084:     dc.w $6839, $E00,$ECF3  ; DATA XREF: ROM:stru_EA5DC   o ROM:stru_EA61C   o
                dc.w $6858, $400,$F409
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $EFB
                dc.w $6810, $E00,$FEF1
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DEF1
word_EA0AE:     dc.w $6839, $E00,$EEF2  ; DATA XREF: ROM:stru_EA5DC   o ROM:stru_EA67C   o
                dc.w $6858, $400,$F608
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $FFA
                dc.w $6810, $E00,$FFF0
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DFF0
word_EA0D8:     dc.w $6839, $E00,$EFF1  ; DATA XREF: ROM:stru_EA5DC   o
                dc.w $6858, $400,$F707
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $FFA
                dc.w $6810, $E00,$FFEF
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DFEF
word_EA102:     dc.w $6839, $E00,$EFF1  ; DATA XREF: ROM:stru_EA67C   o
                dc.w $6858, $400,$F707
                dc.w $6835, $500,$12F4
                dc.w $6830,    0,$10FA
                dc.w $6810, $E00, $1EF
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$E1EF
word_EA12C:     dc.w $6839, $E00,$F0F3  ; DATA XREF: ROM:stru_EA5B8   o ROM:stru_EA5F8   o
                dc.w $6830,    0, $FF7
                dc.w $6810, $E00,  $F1
                dc.w $6835, $500,$1202
                dc.w $6835, $500,$12ED
                dc.w $6858, $400,$F809
                dc.w $E800, $F00,$E0F1
word_EA156:     dc.w $6839, $E00,$ECF3  ; DATA XREF: ROM:stru_EA5B8   o ROM:stru_EA5F8   o
                dc.w $6831, $500, $BF0
                dc.w $6830,    0, $BFA
                dc.w $6810, $E00,$FDF1
                dc.w $6835, $500,$12FF
                dc.w $6858, $400,$F409
                dc.w $E800, $F00,$DDF1
word_EA180:     dc.w $6831, $500, $5F8  ; DATA XREF: ROM:stru_EA5B8   o ROM:stru_EA5F8   o
                dc.w $6835, $500,$12F8
                dc.w $6839, $E00,$E8F3
                dc.w $6858, $400,$F009
                dc.w $6810, $E00,$FAF1
                dc.w $E800, $F00,$DAF1
word_EA1A4:     dc.w $6831, $500, $B02  ; DATA XREF: ROM:stru_EA5B8   o ROM:stru_EA5F8   o
                dc.w $6835, $500,$12F1
                dc.w $6830,    0, $A00
                dc.w $6839, $E00,$ECF3
                dc.w $6858, $400,$F409
                dc.w $6810, $E00,$FDF1
                dc.w $E800, $F00,$DDF1
word_EA1CE:     dc.w $6835, $500,$1202  ; DATA XREF: ROM:stru_EA5B8   o ROM:stru_EA5F8   o
                dc.w $6835, $500,$12ED
                dc.w $6830,    0, $F00
                dc.w $6839, $E00,$F0F3
                dc.w $6858, $400,$F809
                dc.w $6810, $E00,  $F1
                dc.w $E800, $F00,$E0F1
word_EA1F8:     dc.w $6839, $E00,$ECF3  ; DATA XREF: ROM:stru_EA5B8   o ROM:stru_EA5F8   o
                dc.w $6835, $500,$12FE
                dc.w $6830,    0, $DFF
                dc.w $6810, $E00,$FDF1
                dc.w $6831, $500, $BF0
                dc.w $6858, $400,$F409
                dc.w $E800, $F00,$DDF1
word_EA222:     dc.w $6835, $500,$12F8  ; DATA XREF: ROM:stru_EA5B8   o ROM:stru_EA5F8   o
                dc.w $6830,    0, $CFD
                dc.w $6839, $E00,$E8F3
                dc.w $6858, $400,$F009
                dc.w $6810, $E00,$FAF1
                dc.w $E800, $F00,$DAF1
word_EA246:     dc.w $6835, $500,$12F1  ; DATA XREF: ROM:stru_EA5B8   o ROM:stru_EA5F8   o
                dc.w $6830,    0, $EF9
                dc.w $6839, $E00,$ECF3
                dc.w $6810, $E00,$FDF0
                dc.w $6831, $500, $B02
                dc.w $6858, $400,$F409
                dc.w $E800, $F00,$DDF1
word_EA270:     dc.w $6839, $E00,$ECF0  ; DATA XREF: ROM:stru_EA61C   o
                dc.w $6858, $400,$F405
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $EFA
                dc.w $6810, $E00,$FEF0
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DEF0
word_EA29A:     dc.w $6839, $E00,$ECEE  ; DATA XREF: ROM:stru_EA61C   o
                dc.w $6858, $400,$F402
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $EF9
                dc.w $6810, $E00,$FEEF
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DEEF
word_EA2C4:     dc.w $6839, $E00,$ECED  ; DATA XREF: ROM:stru_EA61C   o
                dc.w $6858, $400,$F400
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $EF9
                dc.w $6810, $E00,$FEEE
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DEEE
word_EA2EE:     dc.w $6845, $A00,$EFF2  ; DATA XREF: ROM:stru_EA67C   o
                dc.w $685A, $500,$E900
                dc.w $6835, $500,$12F4
                dc.w $6830,    0,$10FA
                dc.w $6810, $E00, $3EF
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$E3EF
word_EA318:     dc.w $6845, $A00,$E8F5  ; DATA XREF: ROM:stru_EA634   o
                dc.w $685A, $500,$E204
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $DFB
                dc.w $6810, $E00,$FCF1
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DCF1
word_EA342:     dc.w $6845, $A00,$F1F0  ; DATA XREF: ROM:stru_EA67C   o
                dc.w $685A, $500,$EBFE
                dc.w $6835, $500,$12F4
                dc.w $6830,    0,$11FA
                dc.w $6810, $E00, $5EF
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$E5EF
word_EA36C:     dc.w $684E, $A00,$E8F4  ; DATA XREF: ROM:stru_EA64C   o
                dc.w $685E, $100,$DCFC
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $DFB
                dc.w $6810, $E00,$FCF1
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DCF1
word_EA396:     dc.w $6845, $A00,$EAF3  ; DATA XREF: ROM:stru_EA634   o
                dc.w $685A, $500,$E501
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $EFA
                dc.w $6810, $E00,$FDF0
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DDF0
word_EA3C0:     dc.w $6845, $A00,$EBF2  ; DATA XREF: ROM:stru_EA634   o
                dc.w $685A, $500,$E7FF
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $EFA
                dc.w $6810, $E00,$FEEF
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DEEF
word_EA3EA:     dc.w $6845, $A00,$EDF0  ; DATA XREF: ROM:stru_EA634   o
                dc.w $685A, $500,$E9FD
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $EF9
                dc.w $6810, $E00,$FEEE
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DEEE
word_EA414:     dc.w $684E, $A00,$EBF4  ; DATA XREF: ROM:stru_EA64C   o
                dc.w $685E, $100,$E0FC
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $EFB
                dc.w $6810, $E00,$FDF1
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DDF1
word_EA43E:     dc.w $684E, $A00,$EDF4  ; DATA XREF: ROM:stru_EA64C   o
                dc.w $685E, $100,$E3FC
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $FFB
                dc.w $6810, $E00,$FEF1
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DEF1
word_EA468:     dc.w $684E, $A00,$EEF4  ; DATA XREF: ROM:stru_EA64C   o
                dc.w $685E, $100,$E5FC
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $FFB
                dc.w $6810, $E00,$FFF1
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DFF1
word_EA492:     dc.w $7845, $A00,$ECF4  ; DATA XREF: ROM:stru_EA664   o
                dc.w $785A, $500,$FA02
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $EFB
                dc.w $6810, $E00,$FEF1
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DEF1
word_EA4BC:     dc.w $7845, $A00,$EAF2  ; DATA XREF: ROM:stru_EA664   o
                dc.w $785A, $500,$F7FF
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $DFA
                dc.w $6810, $E00,$FDF0
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DDF0
word_EA4E6:     dc.w $7845, $A00,$E9F1  ; DATA XREF: ROM:stru_EA664   o
                dc.w $785A, $500,$F5FD
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $CFA
                dc.w $6810, $E00,$FCEF
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DCEF
word_EA510:     dc.w $7845, $A00,$E8EF  ; DATA XREF: ROM:stru_EA664   o
                dc.w $785A, $500,$F3FA
                dc.w $6835, $500,$12F4
                dc.w $6830,    0, $CF8
                dc.w $6810, $E00,$FCEE
                dc.w $6835, $500,$12FB
                dc.w $E800, $F00,$DCEE
word_EA53A:     dc.w $6831, $500, $FF1  ; DATA XREF: ROM:stru_EA69C   o ROM:stru_EA6A8   o
                dc.w $6831, $500, $FF7
                dc.w $6845, $A00,$EDF2
                dc.w $685A, $500,$E9FF
                dc.w $6830,    0, $BF8
                dc.w $6810, $E00,$FAEF
                dc.w $E800, $F00,$DAEF
word_EA564:     dc.w $6831, $500,$12F1  ; DATA XREF: ROM:stru_EA69C   o ROM:stru_EA6A8   o
                dc.w $6831, $500,$12F7
                dc.w $6845, $A00,$E9F2
                dc.w $685A, $500,$E5FF
                dc.w $6830,    0, $CF8
                dc.w $6810, $E00,$F9EF
                dc.w $E800, $F00,$D9EF
word_EA58E:     dc.w $6831, $500,$12F1  ; DATA XREF: ROM:stru_EA69C   o ROM:stru_EA6A8   o
                dc.w $6831, $500,$12F7
                dc.w $6845, $A00,$E5F2
                dc.w $685A, $500,$E0FF
                dc.w $6830,    0, $AF8
                dc.w $6810, $E00,$F8EF
                dc.w $E800, $F00,$D8EF
stru_EA5B8:     dc.w word_EA12C-*       ; field_0 ; DATA XREF: ROM:off_2CA90   o ROM:stru_EA5B8   o ...
                dc.w     5              ; field_2
                dc.w word_EA156-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_EA180-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_EA1A4-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_EA1CE-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_EA1F8-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_EA222-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_EA246-*       ; field_0
                dc.w     5              ; field_2
                dc.w stru_EA5B8-*       ; field_0
                dc.w     0              ; field_2
stru_EA5DC:     dc.w word_EA05A-*       ; field_0 ; DATA XREF: ROM:off_2CA90   o ROM:stru_EA5DC   o ...
                dc.w     8              ; field_2
                dc.w word_EA084-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EA0AE-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EA0D8-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EA0AE-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EA084-*       ; field_0
                dc.w     6              ; field_2
                dc.w stru_EA5DC-*       ; field_0
                dc.w     0              ; field_2
stru_EA5F8:     dc.w word_EA246-*       ; field_0 ; DATA XREF: ROM:off_2CA90   o ROM:stru_EA5F8   o ...
                dc.w     6              ; field_2
                dc.w word_EA222-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EA1F8-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EA1CE-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EA1A4-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EA180-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EA156-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EA12C-*       ; field_0
                dc.w     6              ; field_2
                dc.w stru_EA5F8-*       ; field_0
                dc.w     0              ; field_2
stru_EA61C:     dc.w word_EA084-*       ; field_0 ; DATA XREF: ROM:off_2CA90   o ROM:off_2CB56   o ...
                dc.w     2              ; field_2
                dc.w word_EA270-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA29A-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA2C4-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA29A-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA270-*       ; field_0
                dc.w   $FF              ; field_2
stru_EA634:     dc.w word_EA318-*       ; field_0 ; DATA XREF: ROM:off_2CA90   o ROM:off_2CB56   o ...
                dc.w     2              ; field_2
                dc.w word_EA396-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA3C0-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA3EA-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA3C0-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA396-*       ; field_0
                dc.w   $FF              ; field_2
stru_EA64C:     dc.w word_EA36C-*       ; field_0 ; DATA XREF: ROM:off_2CA90   o ROM:off_2CB56   o ...
                dc.w     2              ; field_2
                dc.w word_EA414-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA43E-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA468-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA43E-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA414-*       ; field_0
                dc.w   $FF              ; field_2
stru_EA664:     dc.w word_EA492-*       ; field_0 ; DATA XREF: ROM:off_2CA90   o ROM:off_2CB56   o ...
                dc.w     2              ; field_2
                dc.w word_EA4BC-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA4E6-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA510-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA4E6-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA4BC-*       ; field_0
                dc.w   $FF              ; field_2
stru_EA67C:     dc.w word_EA05A-*       ; field_0 ; DATA XREF: ROM:off_2CA90   o ROM:stru_EA67C   o ...
                dc.w     1              ; field_2
                dc.w word_EA0AE-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA102-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_EA2EE-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_EA342-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EA2EE-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_EA102-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA0AE-*       ; field_0
                dc.w   $FF              ; field_2
stru_EA69C:     dc.w word_EA53A-*       ; field_0 ; DATA XREF: ROM:off_2CA90   o sub_2CB86+10   o ...
                dc.w     4              ; field_2
                dc.w word_EA564-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EA58E-*       ; field_0
                dc.w   $FF              ; field_2
stru_EA6A8:     dc.w word_EA58E-*       ; field_0 ; DATA XREF: ROM:off_2CA90   o ROM:stru_EA6A8   o ...
                dc.w     6              ; field_2
                dc.w word_EA564-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EA53A-*       ; field_0
                dc.w   $FF              ; field_2
word_EA6B4:     dc.w $6870,    0,$1AE8  ; DATA XREF: ROM:stru_EA7E0   o ROM:stru_EA814   o
                dc.w $686C, $500, $AE8
                dc.w $681F, $400,$DCEA
                dc.w $6813, $B00,$E4EA
                dc.w $6810, $200, $10D
                dc.w $E800, $F00,$F9ED
word_EA6D8:     dc.w $6870,    0,$19E8  ; DATA XREF: ROM:stru_EA7E0   o ROM:stru_EA814   o
                dc.w $686C, $500, $9E8
                dc.w $682A, $400,$E5EA
                dc.w $6821, $A00,$EDEA
                dc.w $6810, $200, $10D
                dc.w $E800, $F00,$F9ED
word_EA6FC:     dc.w $682C, $A00,$EDEA  ; DATA XREF: ROM:stru_EA7E0   o ROM:stru_EA814   o
                dc.w $6871, $800, $CDF
                dc.w $6810, $200,   $D
                dc.w $E800, $F00,$F8ED
word_EA714:     dc.w $6835, $800,$FEEB  ; DATA XREF: ROM:stru_EA7E0   o ROM:stru_EA814   o
                dc.w $6871, $800, $CDF
                dc.w $6810, $200,   $D
                dc.w $E800, $F00,$F8ED
word_EA72C:     dc.w $7835, $800,  $EC  ; DATA XREF: ROM:stru_EA7E0   o ROM:stru_EA814   o
                dc.w $6871, $800, $BDF
                dc.w $6810, $200,$FF0D
                dc.w $E800, $F00,$F7ED
word_EA744:     dc.w $6838, $A00, $2EE  ; DATA XREF: ROM:stru_EA7E0   o ROM:stru_EA814   o
                dc.w $6871, $800, $BDF
                dc.w $6810, $200,$FF0D
                dc.w $E800, $F00,$F7ED
word_EA75C:     dc.w $684A, $400,$19F0  ; DATA XREF: ROM:stru_EA7E0   o ROM:stru_EA814   o
                dc.w $6841, $A00, $1F0
                dc.w $6871, $800, $ADF
                dc.w $6810, $200,$FE0D
                dc.w $E800, $F00,$F6ED
word_EA77A:     dc.w $684C, $A00, $4F6  ; DATA XREF: ROM:stru_EA848   o ROM:stru_EA85C   o
                dc.w $6862, $500,$10EB
                dc.w $6810, $200, $50D
                dc.w $E800, $F00,$FDED
word_EA792:     dc.w $684C, $A00, $5F7  ; DATA XREF: ROM:stru_EA848   o ROM:stru_EA85C   o
                dc.w $6866, $500,$10EB
                dc.w $6810, $200, $70F
                dc.w $E800, $F00,$FFEF
word_EA7AA:     dc.w $6857, $D00, $8F4  ; DATA XREF: ROM:stru_EA848   o ROM:stru_EA85C   o
                dc.w $686A, $400,$18EB
                dc.w $6810, $200, $90E
                dc.w $E800, $F00, $1EE
word_EA7C2:     dc.w $684C, $A00, $3F4  ; DATA XREF: ROM:stru_EA85C   o
                dc.w $6870,    0,$1BE8
                dc.w $686C, $500, $BE8
                dc.w $6810, $200, $30D
                dc.w $E800, $F00,$FBED
stru_EA7E0:     dc.w word_EA6B4-*       ; field_0 ; DATA XREF: ROM:off_2DAA0   o ROM:stru_EA7E0   o ...
                dc.w     4              ; field_2
                dc.w word_EA6D8-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_EA6FC-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA714-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA72C-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA744-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_EA75C-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EA744-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_EA72C-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA714-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA6FC-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA6D8-*       ; field_0
                dc.w     3              ; field_2
                dc.w stru_EA7E0-*       ; field_0
                dc.w     0              ; field_2
stru_EA814:     dc.w word_EA6B4-*       ; field_0 ; DATA XREF: ROM:off_2DAA0   o ROM:stru_EA814   o ...
                dc.w     2              ; field_2
                dc.w word_EA6D8-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA6FC-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA714-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA72C-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA744-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA75C-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA744-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA72C-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA714-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA6FC-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA6D8-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_EA814-*       ; field_0
                dc.w     0              ; field_2
stru_EA848:     dc.w word_EA77A-*       ; field_0 ; DATA XREF: ROM:off_2DAA0   o ROM:stru_EA848   o ...
                dc.w     6              ; field_2
                dc.w word_EA792-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EA7AA-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EA792-*       ; field_0
                dc.w     4              ; field_2
                dc.w stru_EA848-*       ; field_0
                dc.w     0              ; field_2
stru_EA85C:     dc.w word_EA7AA-*       ; field_0 ; DATA XREF: ROM:off_2DAA0   o ROM:stru_EA85C   o ...
                dc.w     2              ; field_2
                dc.w word_EA792-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA77A-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA7C2-*       ; field_0
                dc.w   $FF              ; field_2
word_EA86C:     dc.w $601C, $400,$1FF0  ; DATA XREF: ROM:stru_EADCA   o ROM:stru_EADDA   o ...
                dc.w $681C, $400,$1F00
                dc.w $600C, $500,$D7F0
                dc.w $680C, $500,$D700
                dc.w $6010, $D00,$E7E0
                dc.w $6810, $D00,$E700
                dc.w $6018, $C00,$17E0
                dc.w $6818, $C00,$1700
                dc.w $602E, $700,$F7F0
                dc.w $682E, $700,$F700
                dc.w $6000, $B00,$F7D8
                dc.w $E800, $B00,$F710
word_EA8B4:     dc.w $6010, $D00,$E7E0  ; DATA XREF: ROM:stru_EADCA   o ROM:stru_EADDA   o ...
                dc.w $6026, $700,$F7F0
                dc.w $6826, $700,$F700
                dc.w $601C, $400,$1FF0
                dc.w $681C, $400,$1F00
                dc.w $600C, $500,$D7F0
                dc.w $680C, $500,$D700
                dc.w $6810, $D00,$E700
                dc.w $6018, $C00,$17E0
                dc.w $6818, $C00,$1700
                dc.w $6000, $B00,$F7D8
                dc.w $E800, $B00,$F710
word_EA8FC:     dc.w $601E, $700,$F7F0  ; DATA XREF: ROM:stru_EADCA   o ROM:stru_EADDA   o ...
                dc.w $681E, $700,$F700
                dc.w $601C, $400,$1FF0
                dc.w $681C, $400,$1F00
                dc.w $600C, $500,$D7F0
                dc.w $680C, $500,$D700
                dc.w $6010, $D00,$E7E0
                dc.w $6810, $D00,$E700
                dc.w $6018, $C00,$17E0
                dc.w $6818, $C00,$1700
                dc.w $6000, $B00,$F7D8
                dc.w $E800, $B00,$F710
word_EA944:     dc.w $683E, $500,$FFF8  ; DATA XREF: ROM:stru_EADCA   o ROM:stru_EADDA   o ...
                dc.w $6036, $700,$F7F0
                dc.w $6836, $700,$F700
                dc.w $601C, $400,$1FF0
                dc.w $681C, $400,$1F00
                dc.w $600C, $500,$D7F0
                dc.w $680C, $500,$D700
                dc.w $6010, $D00,$E7E0
                dc.w $6810, $D00,$E700
                dc.w $6018, $C00,$17E0
                dc.w $6818, $C00,$1700
                dc.w $6000, $B00,$F7D8
                dc.w $E800, $B00,$F710
word_EA992:     dc.w $683E, $500,$FFFA  ; DATA XREF: ROM:stru_EAE06   o
                dc.w $6036, $700,$F7F0
                dc.w $6836, $700,$F700
                dc.w $601C, $400,$1FF0
                dc.w $681C, $400,$1F00
                dc.w $600C, $500,$D7F0
                dc.w $680C, $500,$D700
                dc.w $6010, $D00,$E7E0
                dc.w $6810, $D00,$E700
                dc.w $6018, $C00,$17E0
                dc.w $6818, $C00,$1700
                dc.w $6000, $B00,$F7D8
                dc.w $E800, $B00,$F710
word_EA9E0:     dc.w $683E, $500,$FFFC  ; DATA XREF: ROM:stru_EAE06   o
                dc.w $6036, $700,$F7F0
                dc.w $6836, $700,$F700
                dc.w $601C, $400,$1FF0
                dc.w $681C, $400,$1F00
                dc.w $600C, $500,$D7F0
                dc.w $680C, $500,$D700
                dc.w $6010, $D00,$E7E0
                dc.w $6810, $D00,$E700
                dc.w $6018, $C00,$17E0
                dc.w $6818, $C00,$1700
                dc.w $6000, $B00,$F7D8
                dc.w $E800, $B00,$F710
word_EAA2E:     dc.w $683E, $500,$FFFD  ; DATA XREF: ROM:stru_EAE06   o
                dc.w $6036, $700,$F7F0
                dc.w $6836, $700,$F700
                dc.w $601C, $400,$1FF0
                dc.w $681C, $400,$1F00
                dc.w $600C, $500,$D7F0
                dc.w $680C, $500,$D700
                dc.w $6010, $D00,$E7E0
                dc.w $6810, $D00,$E700
                dc.w $6018, $C00,$17E0
                dc.w $6818, $C00,$1700
                dc.w $6000, $B00,$F7D8
                dc.w $E800, $B00,$F710
word_EAA7C:     dc.w $683E, $500,$FFF6  ; DATA XREF: ROM:stru_EAE06   o
                dc.w $6036, $700,$F7F0
                dc.w $6836, $700,$F700
                dc.w $601C, $400,$1FF0
                dc.w $681C, $400,$1F00
                dc.w $600C, $500,$D7F0
                dc.w $680C, $500,$D700
                dc.w $6010, $D00,$E7E0
                dc.w $6810, $D00,$E700
                dc.w $6018, $C00,$17E0
                dc.w $6818, $C00,$1700
                dc.w $6000, $B00,$F7D8
                dc.w $E800, $B00,$F710
word_EAACA:     dc.w $683E, $500,$FFF4  ; DATA XREF: ROM:stru_EAE06   o
                dc.w $6036, $700,$F7F0
                dc.w $6836, $700,$F700
                dc.w $601C, $400,$1FF0
                dc.w $681C, $400,$1F00
                dc.w $600C, $500,$D7F0
                dc.w $680C, $500,$D700
                dc.w $6010, $D00,$E7E0
                dc.w $6810, $D00,$E700
                dc.w $6018, $C00,$17E0
                dc.w $6818, $C00,$1700
                dc.w $6000, $B00,$F7D8
                dc.w $E800, $B00,$F710
word_EAB18:     dc.w $683E, $500,$FFF3  ; DATA XREF: ROM:stru_EAE06   o
                dc.w $6036, $700,$F7F0
                dc.w $6836, $700,$F700
                dc.w $601C, $400,$1FF0
                dc.w $681C, $400,$1F00
                dc.w $600C, $500,$D7F0
                dc.w $680C, $500,$D700
                dc.w $6010, $D00,$E7E0
                dc.w $6810, $D00,$E700
                dc.w $6018, $C00,$17E0
                dc.w $6818, $C00,$1700
                dc.w $6000, $B00,$F7D8
                dc.w $E800, $B00,$F710
word_EAB66:     dc.w $6026, $700,$F7F0  ; DATA XREF: ROM:stru_EAE3A   o ROM:stru_EAE4A   o
                dc.w $6826, $700,$F700
                dc.w $6018, $C00,$17E0
                dc.w $6000, $B00,$F7D8
                dc.w $604E, $A00, $DD8
                dc.w $6818, $C00,$1700
                dc.w $6800, $B00,$F710
                dc.w $684E, $A00, $D10
                dc.w $601C, $400,$1FF0
                dc.w $681C, $400,$1F00
                dc.w $600C, $500,$D7F0
                dc.w $680C, $500,$D700
                dc.w $6010, $D00,$E7E0
                dc.w $E810, $D00,$E700
word_EABBA:     dc.w $602E, $700,$F4F0  ; DATA XREF: ROM:stru_EAE3A   o ROM:stru_EAE4A   o
                dc.w $682E, $700,$F400
                dc.w $6018, $C00,$14E0
                dc.w $6000, $B00,$F4D8
                dc.w $604E, $A00, $DD9
                dc.w $6818, $C00,$1400
                dc.w $6800, $B00,$F410
                dc.w $684E, $A00, $D0F
                dc.w $601C, $400,$1CF0
                dc.w $681C, $400,$1C00
                dc.w $600C, $500,$D4F0
                dc.w $680C, $500,$D400
                dc.w $6010, $D00,$E4E0
                dc.w $E810, $D00,$E400
word_EAC0E:     dc.w $6026, $700,$F1F0  ; DATA XREF: ROM:stru_EAE3A   o ROM:stru_EAE4A   o
                dc.w $6826, $700,$F1FF
                dc.w $6018, $C00,$11E0
                dc.w $6000, $B00,$F1D8
                dc.w $6048, $600, $EE0
                dc.w $6800, $B00,$F110
                dc.w $6818, $C00,$1100
                dc.w $6848, $600, $E10
                dc.w $601C, $400,$19F0
                dc.w $681C, $400,$1900
                dc.w $600C, $500,$D1F0
                dc.w $680C, $500,$D100
                dc.w $6010, $D00,$E1E0
                dc.w $E810, $D00,$E100
word_EAC62:     dc.w $6000, $B00,$EED8  ; DATA XREF: ROM:stru_EAE3A   o ROM:stru_EAE5A   o
                dc.w $6818, $C00, $E00
                dc.w $6800, $B00,$EE10
                dc.w $6018, $C00, $EE0
                dc.w $6042, $600, $DDE
                dc.w $6842, $600, $D12
                dc.w $683E, $500,$F6F4
                dc.w $6836, $700,$EE00
                dc.w $6036, $700,$EEF0
                dc.w $601C, $400,$16F0
                dc.w $681C, $400,$1600
                dc.w $600C, $500,$CEF0
                dc.w $680C, $500,$CE00
                dc.w $6010, $D00,$DEE0
                dc.w $E810, $D00,$DE00
word_EACBC:     dc.w $6000, $B00,$EED8  ; DATA XREF: ROM:stru_EAE5A   o
                dc.w $6818, $C00, $E00
                dc.w $6800, $B00,$EE10
                dc.w $6018, $C00, $EE0
                dc.w $6042, $600, $DDC
                dc.w $6842, $600, $D14
                dc.w $683E, $500,$F6F4
                dc.w $6836, $700,$EE00
                dc.w $6036, $700,$EEF0
                dc.w $601C, $400,$16F0
                dc.w $681C, $400,$1600
                dc.w $600C, $500,$CEF0
                dc.w $680C, $500,$CE00
                dc.w $6010, $D00,$DEE0
                dc.w $E810, $D00,$DE00
word_EAD16:     dc.w $6000, $B00,$EFD8  ; DATA XREF: ROM:stru_EAE5A   o
                dc.w $6018, $C00, $FE0
                dc.w $6818, $C00, $F00
                dc.w $6800, $B00,$EF10
                dc.w $6048, $600, $DDB
                dc.w $6848, $600, $D16
                dc.w $683E, $500,$F7F4
                dc.w $6836, $700,$EF00
                dc.w $6036, $700,$EFF0
                dc.w $601C, $400,$17F0
                dc.w $681C, $400,$1700
                dc.w $600C, $500,$CFF0
                dc.w $680C, $500,$CF00
                dc.w $6010, $D00,$DFE0
                dc.w $E810, $D00,$DF00
word_EAD70:     dc.w $6000, $B00,$F0D8  ; DATA XREF: ROM:stru_EAE5A   o
                dc.w $6018, $C00,$10E0
                dc.w $6818, $C00,$1000
                dc.w $6800, $B00,$F010
                dc.w $604E, $A00, $DD1
                dc.w $684E, $A00, $D18
                dc.w $683E, $500,$F8F4
                dc.w $6836, $700,$F000
                dc.w $6036, $700,$F0F0
                dc.w $601C, $400,$18F0
                dc.w $681C, $400,$1800
                dc.w $600C, $500,$D0F0
                dc.w $680C, $500,$D000
                dc.w $6010, $D00,$E0E0
                dc.w $E810, $D00,$E000
stru_EADCA:     dc.w word_EA86C-*       ; field_0 ; DATA XREF: ROM:off_2D004   o ROM:stru_EADCA   o ...
                dc.w     2              ; field_2
                dc.w word_EA8B4-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA8FC-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA944-*       ; field_0
                dc.w   $FF              ; field_2
stru_EADDA:     dc.w word_EA944-*       ; field_0 ; DATA XREF: ROM:off_2D004   o ROM:stru_EADDA   o ...
                dc.w     2              ; field_2
                dc.w word_EA8FC-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA8B4-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA86C-*       ; field_0
                dc.w   $FF              ; field_2
stru_EADEA:     dc.w word_EA944-*       ; field_0 ; DATA XREF: ROM:off_2D004   o ROM:stru_EADEA   o ...
                dc.w   $70              ; field_2
                dc.w word_EA8FC-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA8B4-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA86C-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA8B4-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EA8FC-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_EADEA-*       ; field_0
                dc.w     0              ; field_2
stru_EAE06:     dc.w word_EA944-*       ; field_0 ; DATA XREF: ROM:off_2D004   o ROM:stru_EAE06   o ...
                dc.w     2              ; field_2
                dc.w word_EA992-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA9E0-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAA2E-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA9E0-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA992-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA944-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAA7C-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAACA-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAB18-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAACA-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAA7C-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EA944-*       ; field_0
                dc.w   $FF              ; field_2
stru_EAE3A:     dc.w word_EAB66-*       ; field_0 ; DATA XREF: ROM:off_2D004   o ROM:stru_EAE3A   o ...
                dc.w     4              ; field_2
                dc.w word_EABBA-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EAC0E-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EAC62-*       ; field_0
                dc.w   $FF              ; field_2
stru_EAE4A:     dc.w word_EAC0E-*       ; field_0 ; DATA XREF: ROM:off_2D004   o ROM:stru_EAE4A   o ...
                dc.w     5              ; field_2
                dc.w word_EABBA-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_EAB66-*       ; field_0
                dc.w     5              ; field_2
                dc.w word_EA944-*       ; field_0
                dc.w   $FF              ; field_2
stru_EAE5A:     dc.w word_EAC62-*       ; field_0 ; DATA XREF: ROM:off_2D004   o ROM:stru_EAE5A   o ...
                dc.w     2              ; field_2
                dc.w word_EACBC-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAD16-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAD70-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAD16-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EACBC-*       ; field_0
                dc.w     2              ; field_2
                dc.w stru_EAE5A-*       ; field_0
                dc.w     0              ; field_2
                dc.w $680C, $F00,$EFE9
                dc.w $6808, $500,$DFF9
                dc.w $6800, $700,$D709
                dc.w $6840,    0,$D919
                dc.w $6824,    0,  $18
                dc.w $6825, $D00,  $F8
                dc.w $E81C, $D00,$F008
                dc.w $680C, $F00,$F0EA
                dc.w $6808, $500,$E0FA
                dc.w $6800, $700,$D80A
                dc.w $6840,    0,$DA1A
                dc.w $6824,    0,$FF17
                dc.w $6825, $D00,$FFF7
                dc.w $E81C, $D00,$EF07
                dc.w $680C, $F00,$F1EA
                dc.w $6808, $500,$E1FA
                dc.w $6800, $700,$D90A
                dc.w $6840,    0,$DB1A
                dc.w $682D, $500,$FE0B
                dc.w $6837, $A00,$E60B
                dc.w $E831, $600,$F6FB
                dc.w $680C, $F00,$F2EB
                dc.w $6808, $500,$E2FB
                dc.w $6800, $700,$DA0B
                dc.w $6840,    0,$DC1B
                dc.w $682D, $500,$FE0A
                dc.w $6837, $A00,$E60A
                dc.w $E831, $600,$F6FA
word_EAF1E:     dc.w $604D, $500, $6F4  ; DATA XREF: ROM:stru_EB278   o ROM:stru_EB2CC   o
                dc.w $6851, $D00,$13ED
                dc.w $6841, $500,$FCF3
                dc.w $6849, $500, $2EC
                dc.w $680C, $F00,$EEE3
                dc.w $6808, $500,$DEF3
                dc.w $6800, $700,$D603
                dc.w $6840,    0,$D813
                dc.w $6824,    0,$FF12
                dc.w $6825, $D00,$FFF2
                dc.w $E81C, $D00,$EF02
word_EAF60:     dc.w $604D, $500, $7F6  ; DATA XREF: ROM:stru_EB278   o ROM:stru_EB294   o ...
                dc.w $6851, $D00,$13ED
                dc.w $6841, $500,$FEF5
                dc.w $6849, $500, $1F0
                dc.w $680C, $F00,$F0E6
                dc.w $6808, $500,$E0F6
                dc.w $6800, $700,$D806
                dc.w $6840,    0,$DA16
                dc.w $6824,    0,$FF13
                dc.w $6825, $D00,$FFF3
                dc.w $E81C, $D00,$EF03
word_EAFA2:     dc.w $7049, $500, $AF7  ; DATA XREF: ROM:stru_EB278   o ROM:stru_EB294   o ...
                dc.w $6851, $D00,$13ED
                dc.w $6041, $500, $5FD
                dc.w $6845, $500, $3F2
                dc.w $680C, $F00,$F1E8
                dc.w $6808, $500,$E1F8
                dc.w $6800, $700,$D908
                dc.w $6840,    0,$DB18
                dc.w $682D, $500,$FE09
                dc.w $6837, $A00,$E609
                dc.w $E831, $600,$F6F9
word_EAFE4:     dc.w $6841, $500, $902  ; DATA XREF: ROM:stru_EB278   o ROM:stru_EB294   o ...
                dc.w $7845, $500, $DF8
                dc.w $6845, $500, $6F8
                dc.w $6851, $D00,$13ED
                dc.w $680C, $F00,$F2EB
                dc.w $6808, $500,$E2FB
                dc.w $6800, $700,$DA0B
                dc.w $6840,    0,$DC1B
                dc.w $682D, $500,$FE0A
                dc.w $6837, $A00,$E60A
                dc.w $E831, $600,$F6FA
word_EB026:     dc.w $7049, $500, $BF9  ; DATA XREF: ROM:stru_EB294   o
                dc.w $6841, $500, $402
                dc.w $6845, $500, $3FB
                dc.w $6851, $D00,$13ED
                dc.w $680C, $F00,$EEEF
                dc.w $6808, $500,$DEFF
                dc.w $6800, $700,$D60F
                dc.w $6840,    0,$D81F
                dc.w $682D, $500,$FA0E
                dc.w $6837, $A00,$E20E
                dc.w $E831, $600,$F2FE
word_EB068:     dc.w $7049, $500, $AF9  ; DATA XREF: ROM:stru_EB294   o
                dc.w $6851, $D00,$13ED
                dc.w $6841, $500, $300
                dc.w $6049, $500,$FBF9
                dc.w $680C, $F00,$E8F1
                dc.w $6808, $500,$D801
                dc.w $6800, $700,$D011
                dc.w $6840,    0,$D221
                dc.w $682D, $500,$F410
                dc.w $6837, $A00,$DC10
                dc.w $E831, $600,$EC00
word_EB0AA:     dc.w $7049, $500, $9F0  ; DATA XREF: ROM:stru_EB294   o ROM:stru_EB2B4   o
                dc.w $6859, $A00,$12E5
                dc.w $604D, $500,$F9F5
                dc.w $6841, $500, $3F4
                dc.w $680C, $F00,$E2EF
                dc.w $6808, $500,$D2FF
                dc.w $6800, $700,$CA0F
                dc.w $6840,    0,$CC1F
                dc.w $682D, $500,$EE0E
                dc.w $6837, $A00,$D60E
                dc.w $E831, $600,$E6FE
word_EB0EC:     dc.w $6841, $500, $9FF  ; DATA XREF: ROM:stru_EB294   o
                dc.w $7845, $500, $DF5
                dc.w $6845, $500, $7F5
                dc.w $6851, $D00,$13ED
                dc.w $680C, $F00,$F6E7
                dc.w $6808, $500,$E6F7
                dc.w $6800, $700,$DE07
                dc.w $6840,    0,$E017
                dc.w $682D, $500, $206
                dc.w $6837, $A00,$EA06
                dc.w $E831, $600,$FAF6
word_EB12E:     dc.w $7049, $500, $BF3  ; DATA XREF: ROM:stru_EB2B4   o
                dc.w $6859, $A00,$14E8
                dc.w $604D, $500,$FBF3
                dc.w $6841, $500, $5F5
                dc.w $680C, $F00,$E4ED
                dc.w $6808, $500,$D4FD
                dc.w $6800, $700,$CC0D
                dc.w $6840,    0,$CE1D
                dc.w $682D, $500,$F00C
                dc.w $6837, $A00,$D80C
                dc.w $E831, $600,$E8FC
word_EB170:     dc.w $604D, $500, $EF5  ; DATA XREF: ROM:stru_EB2B4   o
                dc.w $6859, $A00,$1AEE
                dc.w $604D, $500,$FCF4
                dc.w $6841, $500, $5F5
                dc.w $680C, $F00,$E5EC
                dc.w $6808, $500,$D5FC
                dc.w $6800, $700,$CD0C
                dc.w $6840,    0,$CF1C
                dc.w $682D, $500,$F10B
                dc.w $6837, $A00,$D90B
                dc.w $E831, $600,$E9FB
word_EB1B2:     dc.w $6049, $500,$FBF6  ; DATA XREF: ROM:stru_EB2B4   o
                dc.w $604D, $500, $BFA
                dc.w $6859, $A00,$17F2
                dc.w $6841, $500, $4FB
                dc.w $680C, $F00,$E5EB
                dc.w $6808, $500,$D5FB
                dc.w $6800, $700,$CD0B
                dc.w $6840,    0,$CF1B
                dc.w $682D, $500,$F10A
                dc.w $6837, $A00,$D90A
                dc.w $E831, $600,$E9FA
word_EB1F4:     dc.w $6845, $500,$FAF6  ; DATA XREF: ROM:stru_EB2B4   o
                dc.w $604D, $500, $7FF
                dc.w $6859, $A00,$13F7
                dc.w $6841, $500,$FEFE
                dc.w $680C, $F00,$E6EA
                dc.w $6808, $500,$D6FA
                dc.w $6800, $700,$CE0A
                dc.w $6840,    0,$D01A
                dc.w $682D, $500,$F209
                dc.w $6837, $A00,$DA09
                dc.w $E831, $600,$EAF9
word_EB236:     dc.w $6049, $500, $305  ; DATA XREF: ROM:stru_EB2B4   o
                dc.w $6851, $D00, $D04
                dc.w $6845, $500,$FAF7
                dc.w $6841, $500,$FDFF
                dc.w $680C, $F00,$E6E9
                dc.w $6808, $500,$D6F9
                dc.w $6800, $700,$CE09
                dc.w $6840,    0,$D019
                dc.w $682D, $500,$F208
                dc.w $6837, $A00,$DA08
                dc.w $E831, $600,$EAF8
stru_EB278:     dc.w word_EAF1E-*       ; field_0 ; DATA XREF: ROM:off_2E0AE   o ROM:stru_EB278   o ...
                dc.w     4              ; field_2
                dc.w word_EAF60-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAFA2-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAFE4-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EAFA2-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAF60-*       ; field_0
                dc.w     2              ; field_2
                dc.w stru_EB278-*       ; field_0
                dc.w     0              ; field_2
stru_EB294:     dc.w word_EAF60-*       ; field_0 ; DATA XREF: ROM:off_2E0AE   o ROM:stru_EB294   o ...
                dc.w     2              ; field_2
                dc.w word_EAFA2-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAFE4-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_EB0EC-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EAFE4-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_EB026-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EB068-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EB0AA-*       ; field_0
                dc.w   $FF              ; field_2
stru_EB2B4:     dc.w word_EB0AA-*       ; field_0 ; DATA XREF: ROM:off_2E0AE   o sub_2E242+10   o ...
                dc.w     6              ; field_2
                dc.w word_EB12E-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EB170-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EB1B2-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EB1F4-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EB236-*       ; field_0
                dc.w   $FF              ; field_2
stru_EB2CC:     dc.w word_EAF1E-*       ; field_0 ; DATA XREF: ROM:off_2E0AE   o ROM:stru_EB2CC   o ...
                dc.w     1              ; field_2
                dc.w word_EAF60-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EAFA2-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_EAFE4-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EAFA2-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_EAF60-*       ; field_0
                dc.w   $FF              ; field_2
word_EB2E4:     dc.w $E800, $E00,$F7F0  ; DATA XREF: ROM:stru_EB320   o
word_EB2EA:     dc.w $E80C, $E00,$F6F0  ; DATA XREF: ROM:stru_EB320   o
word_EB2F0:     dc.w $E818, $E00,$F6F0  ; DATA XREF: ROM:stru_EB320   o
word_EB2F6:     dc.w $E824, $E00,$F5F0  ; DATA XREF: ROM:stru_EB320   o
word_EB2FC:     dc.w $E830, $E00,$F6F0  ; DATA XREF: ROM:stru_EB320   o
word_EB302:     dc.w $E83C, $B00,$EEF4  ; DATA XREF: ROM:off_2D326   o
word_EB308:     dc.w $E848, $B00,$F0F5  ; DATA XREF: ROM:off_2D326   o
word_EB30E:     dc.w $E854, $F00,$F0F0  ; DATA XREF: ROM:off_2D326   o
word_EB314:     dc.w $E864, $E00,$F5F0  ; DATA XREF: ROM:off_2D326   o
word_EB31A:     dc.w $E870, $E00,$F4EF  ; DATA XREF: ROM:off_2D326   o
stru_EB320:     dc.w word_EB2E4-*       ; field_0 ; DATA XREF: ROM:off_2D2EC   o ROM:stru_EB320   o ...
                dc.w     2              ; field_2
                dc.w word_EB2EA-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EB2F0-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EB2F6-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EB2FC-*       ; field_0
                dc.w     2              ; field_2
                dc.w stru_EB320-*       ; field_0
                dc.w     0              ; field_2
word_EB338:     dc.w $6010, $F00,  $E0  ; DATA XREF: sub_313C4+C   o
                dc.w $6000, $F00,$E0E0
                dc.w $6810, $F00,    0
                dc.w $E800, $F00,$E000
word_EB350:     dc.w $E820, $A00,$F4F4  ; DATA XREF: sub_311AE+C   o
word_EB356:     dc.w $6816, $700,$F4EA  ; DATA XREF: sub_30DCA+C   o
                dc.w $6806, $F00,$F4FA
                dc.w $6802, $C00,$ECF4
                dc.w $E800, $400,$E402
word_EB36E:     dc.w $4009, $A00,  $E8  ; DATA XREF: sub_30CCE+C   o
                dc.w $4809, $A00,    0
                dc.w $4000, $A00,$E8E8
                dc.w $C800, $A00,$E800
word_EB386:     dc.w $4812, $E00,$F600  ; DATA XREF: sub_3058E+C   o
                dc.w $C81E, $F00,$F0E0
word_EB392:     dc.w $6804, $D00,  $F0  ; DATA XREF: ROM:stru_EB3C8   o
                dc.w $6000, $500,$F0F0
                dc.w $E800, $500,$F000
word_EB3A4:     dc.w $680C, $D00,  $F0  ; DATA XREF: ROM:stru_EB3C8   o
                dc.w $6000, $500,$F0F0
                dc.w $E800, $500,$F000
word_EB3B6:     dc.w $6814, $D00,  $F0  ; DATA XREF: ROM:stru_EB3C8   o
                dc.w $6000, $500,$F0F0
                dc.w $E800, $500,$F000
stru_EB3C8:     dc.w word_EB392-*       ; field_0 ; DATA XREF: sub_32F84+38   o ROM:stru_EB3C8   o ...
                dc.w     3              ; field_2
                dc.w word_EB3A4-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_EB3B6-*       ; field_0
                dc.w     3              ; field_2
                dc.w stru_EB3C8-*       ; field_0
                dc.w     0              ; field_2
word_EB3D8:     dc.w $6800, $700,$E5F8  ; DATA XREF: sub_33956+6   o ROM:stru_EB492   o
                dc.w $E808, $700,$FAF8
word_EB3E4:     dc.w $6800, $700,$E3F8  ; DATA XREF: ROM:stru_EB492   o
                dc.w $E808, $700,$FCF8
word_EB3F0:     dc.w $6800, $700,$E1F8  ; DATA XREF: ROM:stru_EB492   o
                dc.w $E808, $700,$FEF8
word_EB3FC:     dc.w $6800, $700,$E0F8  ; DATA XREF: sub_33976+6   o sub_33B54+14   o ...
                dc.w $E808, $700,$FFF8
word_EB408:     dc.w $6842, $D00, $5EF  ; DATA XREF: sub_2EABE+A   o ent_113_state14:loc_2EDFA   o ...
                dc.w $6810, $F00,$F600
                dc.w $684A, $100, $5E7
                dc.w $6820, $E00,$F6E0
                dc.w $683A, $100,$E6DF
                dc.w $682C, $400, $EEF
                dc.w $E82E, $E00,$DEE7
word_EB432:     dc.w $683A, $100,$E6DF  ; DATA XREF: ent_113_stateA+24   o ent_113_state16:loc_2EE32   o
                dc.w $6852, $700, $5EF
                dc.w $684C, $600, $5FF
                dc.w $6820, $E00,$F6E0
                dc.w $6810, $F00,$F600
                dc.w $682C, $400, $EEF
                dc.w $E82E, $E00,$DEE7
word_EB45C:     dc.w $6860, $600,$F4ED  ; DATA XREF: ent_113_state10+28   o
                dc.w $685A, $600,$FCFD
                dc.w $6820, $E00,$F6E0
                dc.w $6810, $F00,$F600
                dc.w $683A, $100,$E6DF
                dc.w $682C, $400, $EEF
                dc.w $E82E, $E00,$DEE7
word_EB486:     dc.w $683C, $C00,  $F6  ; DATA XREF: ent_113_state0+1C   o
                dc.w $E840, $400,$F8F6
stru_EB492:     dc.w word_EB3D8-*       ; field_0 ; DATA XREF: sub_33A92+1C   o ROM:stru_EB492   o ...
                dc.w     1              ; field_2
                dc.w word_EB3E4-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EB3F0-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EB3FC-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EB3FC-*       ; field_0
                dc.w   $FF              ; field_2
word_EB4A6:     dc.w $603A, $600,$F4F0  ; DATA XREF: sub_2FF1C+B8   o ROM:off_3007C   o
                dc.w $E800, $A00,$F400
word_EB4B2:     dc.w $6809,    0,$F313  ; DATA XREF: ROM:off_3007C   o
                dc.w $6819,    0, $BFB
                dc.w $6816, $800, $3F3
                dc.w $E80A, $E00,$EBF3
word_EB4CA:     dc.w $7823, $900,  $F6  ; DATA XREF: ROM:off_3007C   o
                dc.w $E81A, $A00,$E8F6
word_EB4D6:     dc.w $6838,    0,$FBED  ; DATA XREF: ROM:off_3007C   o
                dc.w $6839,    0,$1305
                dc.w $6835, $200,$F3F5
                dc.w $E829, $B00,$F3FD
word_EB4EE:     dc.w $603A, $600,$F4F0  ; DATA XREF: ROM:off_30028   o ROM:off_300BC   o
                dc.w $E83A, $600,$F400
word_EB4FA:     dc.w $6848, $800, $3F3  ; DATA XREF: ROM:off_300BC   o
                dc.w $E840, $D00,$F3F3
word_EB506:     dc.w $7823, $900,  $F6  ; DATA XREF: ROM:off_300BC   o
                dc.w $E823, $900,$F0F6
word_EB512:     dc.w $6048, $800, $4F6  ; DATA XREF: ROM:off_300BC   o
                dc.w $E040, $D00,$F4EE
word_EB51E:     dc.w $685D,    0,$F0F4  ; DATA XREF: ROM:off_30028   o ROM:off_300FC   o
                dc.w $E855, $D00,$F8EC
word_EB52A:     dc.w $6866,    0, $BF7  ; DATA XREF: ROM:off_300FC   o
                dc.w $6867, $200,$FBEF
                dc.w $6864, $400, $3F7
                dc.w $E85E, $900,$F3F7
word_EB542:     dc.w $6854,    0, $2F0  ; DATA XREF: ROM:off_300FC   o
                dc.w $E84C, $700,$F2F8
word_EB54E:     dc.w $6872,    0,$F6ED  ; DATA XREF: ROM:off_300FC   o
                dc.w $6873, $800,$EEED
                dc.w $6870, $100,$F6F5
                dc.w $E86A, $600,$F6FD
stru_EB566:     dc.w word_EB58C-*       ; field_0 ; DATA XREF: sub_30230+12   o ROM:stru_EB566   o ...
                dc.w     4              ; field_2
                dc.w word_EB586-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EB58C-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EB586-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EB58C-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EB586-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EB58C-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EB58C-*       ; field_0
                dc.w   $FF              ; field_2
word_EB586:     dc.w $8876, $500,$F8F8  ; DATA XREF: ROM:stru_EB566   o
word_EB58C:     dc.w $887A,    0,$FCFC  ; DATA XREF: ROM:stru_EB566   o
word_EB592:     dc.w $6812, $400,$FCE0  ; DATA XREF: sub_34198   o
                dc.w $780C, $600,  $F0
                dc.w $680C, $600,$E8F0
                dc.w $7800, $E00,    0
                dc.w $E800, $E00,$E800
word_EB5B0:     dc.w $E814, $A00,$F4F4  ; DATA XREF: sub_34198+5E   o
word_EB5B6:     dc.w $2128, $600, $7F1  ; DATA XREF: ROM:off_3D37A   o
                dc.w $2928, $600, $701
                dc.w $2122, $600,$EFF1
                dc.w $A922, $600,$EF01
word_EB5CE:     dc.w $212E, $600, $7F1  ; DATA XREF: ROM:off_3D37A   o
                dc.w $292E, $600, $701
                dc.w $2122, $600,$EFF1
                dc.w $A922, $600,$EF01
word_EB5E6:     dc.w $211A, $700,$F0F1  ; DATA XREF: update_ent_4F+18   o
                dc.w $A91A, $700,$F001
word_EB5F2:     dc.w $2134, $600, $7F1  ; DATA XREF: ROM:off_3D37A   o
                dc.w $2934, $600, $701
                dc.w $2122, $600,$EFF1
                dc.w $A922, $600,$EF01
word_EB60A:     dc.w $2142, $700,$EFF1  ; DATA XREF: ROM:off_3D40A   o
                dc.w $A942, $700,$EF01
word_EB616:     dc.w $214A, $700,$EFF1  ; DATA XREF: ROM:off_3D40A   o
                dc.w $A94A, $700,$EF01
word_EB622:     dc.w $2152, $700,$EFF1  ; DATA XREF: update_ent_A2+24   o
                dc.w $A952, $700,$EF01
word_EB62E:     dc.w $A95A, $A00,$F5F5  ; DATA XREF: sub_3D562+76   o ROM:stru_EB640   o
word_EB634:     dc.w $A963, $A00,$F7F3  ; DATA XREF: ROM:stru_EB640   o
word_EB63A:     dc.w $A96C, $500,$F8F8  ; DATA XREF: ROM:stru_EB640   o
stru_EB640:     dc.w word_EB62E-*       ; field_0 ; DATA XREF: ROM:stru_EB640   o ROM:stru_EB640   o ...
                dc.w     8              ; field_2
                dc.w word_EB634-*       ; field_0
                dc.w     4              ; field_2
                dc.w word_EB63A-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_EB634-*       ; field_0
                dc.w     4              ; field_2
                dc.w stru_EB640-*       ; field_0
                dc.w     0              ; field_2
word_EB654:     dc.w $6804, $E00,$F3EE  ; DATA XREF: sub_3570E+1E   o sub_35D54+36   o ...
                dc.w $E800, $500,$F90E
word_EB660:     dc.w $6832, $900, $BF4  ; DATA XREF: ROM:off_35F6A   o
                dc.w $6826, $E00,$F3ED
                dc.w $E820, $600,$F70D
word_EB672:     dc.w $6050, $B00,$FDE8  ; DATA XREF: ROM:off_35F6A   o
                dc.w $6850, $B00,$FD00
                dc.w $E838, $D00,$EDF0
word_EB684:     dc.w $E86C, $D00,$F8F0  ; DATA XREF: ROM:off_35F7A   o
word_EB68A:     dc.w $E874, $E00,$F2F0  ; DATA XREF: ROM:off_35F7A   o
word_EB690:     dc.w $E88C, $F00,$EFF1  ; DATA XREF: ROM:off_35F7A   o
word_EB696:     dc.w $605C, $F00,$FDE0  ; DATA XREF: sub_35B88+CE   o
                dc.w $685C, $F00,$FD00
                dc.w $E838, $D00,$EDF0
word_EB6A8:     dc.w $E89C, $D00,$F7E9  ; DATA XREF: ROM:off_35FBA   o
word_EB6AE:     dc.w $E8A4, $E00,$EFEA  ; DATA XREF: ROM:off_35FBA   o
word_EB6B4:     dc.w $E8B0, $B00,$E7F4  ; DATA XREF: ROM:off_35FBA   o
word_EB6BA:     dc.w $E8D8, $E00,$F2F1  ; DATA XREF: ROM:off_35F7A   o
word_EB6C0:     dc.w $E8C8, $F00,$F2EF  ; DATA XREF: ROM:off_35F7A   o
word_EB6C6:     dc.w $E8BC, $E00,$F4F1  ; DATA XREF: ROM:off_35F7A   o
word_EB6CC:     dc.w $E880, $E00,$F4F0  ; DATA XREF: ROM:off_35F7A   o
word_EB6D2:     dc.w $E840, $F00,$EDEF  ; DATA XREF: ROM:off_35F7A   o
word_EB6D8:     dc.w $E810, $F00,$EFF0  ; DATA XREF: ROM:off_35F7A   o
                dc.w $68FE, $400,$13ED
                dc.w $68F2, $B00,$F3ED
                dc.w $68F0, $400, $B05
                dc.w $E8E4, $E00,$F305
word_EB6F6:     dc.w $68FE, $400,$19F4  ; DATA XREF: ROM:off_35B1C   o
                dc.w $68F2, $B00,$F9F4
                dc.w $68F0, $400,$110C
                dc.w $E8E4, $E00,$F90C
word_EB70E:     dc.w $6832, $900,$10FA  ; DATA XREF: ROM:off_35B1C   o
                dc.w $6826, $E00,$F8F3
                dc.w $E820, $600,$FC13
word_EB720:     dc.w $4847, $600,$EF03  ; DATA XREF: sub_37A8A+134   o sub_37A8A+1F6   o ...
                dc.w $484D, $400, $7FB
                dc.w $C84F, $500,$F7F3
word_EB732:     dc.w $4840, $500,$EF0B  ; DATA XREF: sub_37A8A+1A2   o sub_37E8C   o ...
                dc.w $4844, $200,$EF03
                dc.w $484D, $400, $7FB
                dc.w $C84F, $500,$F7F3
word_EB74A:     dc.w $C074, $D00,$F8F0  ; DATA XREF: ROM:0003494C   o
word_EB750:     dc.w $C06C, $D00,$F8F0  ; DATA XREF: ROM:0003494C   o
word_EB756:     dc.w $C063, $A00,$F4F4  ; DATA XREF: ROM:0003494C   o
word_EB75C:     dc.w $C05B, $700,$F0F9  ; DATA XREF: ROM:0003494C   o
word_EB762:     dc.w $C853, $700,$F0F8  ; DATA XREF: ROM:0003494C   o
word_EB768:     dc.w $C85B, $700,$EFF8  ; DATA XREF: ROM:0003494C   o
word_EB76E:     dc.w $C863, $A00,$F3F4  ; DATA XREF: ROM:0003494C   o
word_EB774:     dc.w $C86C, $D00,$F7F1  ; DATA XREF: ROM:0003494C   o
word_EB77A:     dc.w $C07C, $D00,$FAEB  ; DATA XREF: ROM:0003496C   o sub_37558+140   o ...
word_EB780:     dc.w $58B8, $500, $1EF  ; DATA XREF: ROM:0003496C   o
                dc.w $D8BC, $900,$F9F7
word_EB78C:     dc.w $58B0, $600,$FAF4  ; DATA XREF: ROM:0003496C   o
                dc.w $D8B6, $400,$FA04
word_EB798:     dc.w $58AF,    0,$F609  ; DATA XREF: ROM:0003496C   o
                dc.w $D8A7, $700,$F6F9
word_EB7A4:     dc.w $D89F, $700,$F5FB  ; DATA XREF: ROM:0003496C   o
word_EB7AA:     dc.w $589B, $500,$F1FA  ; DATA XREF: ROM:0003496C   o
                dc.w $D895, $900, $1FA
word_EB7B6:     dc.w $588D, $900,$FDFB  ; DATA XREF: ROM:0003496C   o
                dc.w $D893, $400,$F5FB
word_EB7C2:     dc.w $588C,    0,$F0F6  ; DATA XREF: ROM:0003496C   o
                dc.w $D884, $D00,$F8F8
word_EB7CE:     dc.w $E86E, $D00,$F8F1  ; DATA XREF: ROM:off_34A46   o
word_EB7D4:     dc.w $E876, $E00,$F4F0  ; DATA XREF: ROM:off_34A46   o
word_EB7DA:     dc.w $E882, $F00,$EFF0  ; DATA XREF: ROM:off_34A46   o
word_EB7E0:     dc.w $E892, $B00,$F0F6  ; DATA XREF: ROM:off_34A46   o
word_EB7E6:     dc.w $F09E, $700,$F0F8  ; DATA XREF: ROM:off_34A46   o
word_EB7EC:     dc.w $F0A6, $B00,$F0F4  ; DATA XREF: ROM:off_34A46   o
word_EB7F2:     dc.w $F0B2, $F00,$F0F0  ; DATA XREF: ROM:off_34A46   o
word_EB7F8:     dc.w $F0C2, $E00,$F2F1  ; DATA XREF: ROM:off_34A46   o
word_EB7FE:     dc.w $60D6, $500,$F806  ; DATA XREF: ROM:off_34A66   o update_ent_2D+476   o ...
                dc.w $E0CE, $D00,$F8E6
word_EB80A:     dc.w $60E2, $600,$F805  ; DATA XREF: ROM:off_34A66   o
                dc.w $E0DA, $D00,$F8E5
word_EB816:     dc.w $60F0, $900,  $F8  ; DATA XREF: ROM:off_34A66   o
                dc.w $E0E8, $D00,$F0E8
word_EB822:     dc.w $60FF, $A00, $1F5  ; DATA XREF: ROM:off_34A66   o
                dc.w $E0F6, $A00,$E9ED
word_EB82E:     dc.w $6110, $500, $4F6  ; DATA XREF: ROM:off_34A66   o
                dc.w $E108, $700,$E4F6
word_EB83A:     dc.w $611C, $900, $2EE  ; DATA XREF: ROM:off_34A66   o
                dc.w $E114, $700,$E2F6
word_EB846:     dc.w $6126, $E00,$F7EA  ; DATA XREF: ROM:off_34A66   o
                dc.w $E122, $500,$E7FF
word_EB852:     dc.w $613A, $600,$E705  ; DATA XREF: ROM:off_34A66   o
                dc.w $E132, $D00,$F8E5
                dc.w $694C, $D00, $6F8
                dc.w $E940, $E00,$EEF0
word_EB86A:     dc.w $695A, $E00,$F2EB  ; DATA XREF: update_ent_2D+148   o
                dc.w $E954, $600,$FA0B
word_EB876:     dc.w $683B, $C00, $6F7  ; DATA XREF: sub_39B1C+4A   o sub_39CEC+2A   o ...
                dc.w $6835, $600,$F6E8
                dc.w $E829, $E00,$EEF7
word_EB888:     dc.w $6843, $400, $EFF  ; DATA XREF: sub_398FE+E0   o sub_39B04+E   o ...
                dc.w $683F, $C00, $6F7
                dc.w $6835, $600,$F6E8
                dc.w $E829, $E00,$EEF7
                dc.w $6851, $800, $BF8
                dc.w $E845, $E00,$F3F0
word_EB8AC:     dc.w $E854, $B00,$EBEF  ; DATA XREF: ROM:off_34AE0   o
word_EB8B2:     dc.w $6868, $400, $3F7  ; DATA XREF: ROM:off_34AE0   o
                dc.w $E860, $D00,$F3E7
word_EB8BE:     dc.w $E86A, $D00,$FBE8  ; DATA XREF: ROM:off_34AE0   o
word_EB8C4:     dc.w $6875, $C00, $2E9  ; DATA XREF: ROM:off_34AE0   o
                dc.w $E872, $800,$FAF1
word_EB8D0:     dc.w $687F, $800, $9EB  ; DATA XREF: ROM:off_34AE0   o
                dc.w $E879, $900,$F9F3
word_EB8DC:     dc.w $6888, $500, $9F3  ; DATA XREF: ROM:off_34AE0   o
                dc.w $E882, $900,$F9F3
word_EB8E8:     dc.w $E88C, $700,$F8FB  ; DATA XREF: ROM:off_34AE0   o
word_EB8EE:     dc.w $6898, $200,$F7FA  ; DATA XREF: ROM:off_34AE0   o
                dc.w $E894, $300,$F702
word_EB8FA:     dc.w $68A1, $100,$F9F1  ; DATA XREF: ROM:off_34AE0   o ROM:off_34B80   o
                dc.w $E89B, $600,$F1F9
word_EB906:     dc.w $68A9, $100,$FAF1  ; DATA XREF: ROM:off_34AE0   o ROM:off_34B80   o
                dc.w $E8A3, $600,$F2F9
word_EB912:     dc.w $68B1,    0,$F1FA  ; DATA XREF: ROM:off_34AE0   o ROM:off_34B80   o
                dc.w $E8AB, $900,$F8F2
word_EB91E:     dc.w $68B8,    0, $7FB  ; DATA XREF: ROM:off_34AE0   o ROM:off_34B80   o
                dc.w $E8B2, $900,$F7F3
word_EB92A:     dc.w $68BF,    0, $8FA  ; DATA XREF: ROM:off_34AE0   o ROM:off_34B80   o
                dc.w $E8B9, $900,$F8F2
word_EB936:     dc.w $68C6,    0, $7FA  ; DATA XREF: ROM:off_34AE0   o ROM:off_34B80   o
                dc.w $E8C0, $900,$F7F2
word_EB942:     dc.w $68CD,    0,$FFF1  ; DATA XREF: ROM:off_34AE0   o ROM:off_34B80   o
                dc.w $E8C7, $600,$F6F9
word_EB94E:     dc.w $68D4,    0,$FD07  ; DATA XREF: ROM:off_34AE0   o ROM:off_34B80   o
                dc.w $E8CE, $600,$F5F7
word_EB95A:     dc.w $E8D5, $B00,$EDF2  ; DATA XREF: ROM:off_34AE0   o
word_EB960:     dc.w $E8E1, $A00,$F3F4  ; DATA XREF: ROM:off_34AE0   o
word_EB966:     dc.w $E8EA, $E00,$F5EE  ; DATA XREF: ROM:off_34AE0   o
word_EB96C:     dc.w $E8F6, $D00,$F7EF  ; DATA XREF: ROM:off_34AE0   o
word_EB972:     dc.w $E8FE, $E00,$F5EE  ; DATA XREF: ROM:off_34AE0   o
word_EB978:     dc.w $E90A, $A00,$F3F4  ; DATA XREF: ROM:off_34AE0   o
word_EB97E:     dc.w $E913, $B00,$F1F2  ; DATA XREF: ROM:off_34AE0   o
word_EB984:     dc.w $E91F, $700,$F0F8  ; DATA XREF: ROM:off_34AE0   o
word_EB98A:     dc.w $793B, $300,$A5FC  ; DATA XREF: update_ent_3D+1B4   o ROM:off_3A0DA   o
                dc.w $7953, $300,$F1FC
                dc.w $693B, $300,$D5FC
                dc.w $F93B, $300,$B5FC
word_EB9A2:     dc.w $792B, $F00,$B6B7  ; DATA XREF: ROM:off_3A0DA   o
                dc.w $792B, $F00,$C7C8
                dc.w $7943, $F00,$ECED
                dc.w $E12B, $F00,$DEDF
word_EB9BA:     dc.w $6927, $C00,$FCA3  ; DATA XREF: ROM:off_3A0DA   o
                dc.w $693F, $C00,$FCF1
                dc.w $6127, $C00,$FCD4
                dc.w $E927, $C00,$FCBB
                dc.w $2892, $500,  $F0
                dc.w $A88A, $D00,    0
                dc.w $2898, $900,$F4E6
                dc.w $A896, $400,$FC06
word_EB9EA:     dc.w $A8C3, $500,$F6F9  ; DATA XREF: ROM:off_36FCE   o
word_EB9F0:     dc.w $A8C7, $500,$F5FA  ; DATA XREF: ROM:off_36FCE   o
word_EB9F6:     dc.w $A8CB, $500,$F6F9  ; DATA XREF: ROM:off_36FCE   o
word_EB9FC:     dc.w $A8CF, $500,$F6F9  ; DATA XREF: ROM:off_36FCE   o
word_EBA02:     dc.w $A8D3, $500,$F7F9  ; DATA XREF: ROM:off_36FCE   o
word_EBA08:     dc.w $B0D7, $500,$F7F7  ; DATA XREF: ROM:off_36FCE   o
word_EBA0E:     dc.w $B0DB, $500,$F7F7  ; DATA XREF: ROM:off_36FCE   o
word_EBA14:     dc.w $B0DF, $500,$F7F7  ; DATA XREF: ROM:off_36FCE   o
                dc.w $287E, $C00, $AEC
                dc.w $287A, $300,$F20C
                dc.w $A86A, $F00,$EAEC
word_EBA2C:     dc.w $2829, $E00,$E4FE  ; DATA XREF: update_ent_45+308   o update_ent_45+398   o ...
                dc.w $2844, $300,$ECF6
                dc.w $2838, $E00,$FCFE
                dc.w $2836, $100,$FC1E
                dc.w $A835,    0,$DCFE
word_EBA4A:     dc.w $2848, $E00,$FCFE  ; DATA XREF: update_ent_45+5BA   o update_ent_45+6B2   o ...
                dc.w $2829, $E00,$E4FE
                dc.w $2844, $300,$ECF6
                dc.w $2836, $100,$FC1E
                dc.w $A835,    0,$DCFE
word_EBA68:     dc.w $30A0, $E00,$F3CE  ; DATA XREF: update_ent_45+12E   o update_ent_45+136   o ...
                dc.w $B0AC, $F00,$F3EE
word_EBA74:     dc.w $30EE,    0, $FE4  ; DATA XREF: ROM:off_3E16C   o
                dc.w $30E5, $A00,$17DD
                dc.w $B0D5, $F00,$F7EC
word_EBA86:     dc.w $28D3, $400, $A12  ; DATA XREF: ROM:off_3E16C   o
                dc.w $28CB, $D00,$120B
                dc.w $28CA,    0, $2F4
                dc.w $28C4, $900, $3FC
                dc.w $A8BC, $D00,$F3F5
word_EBAA4:     dc.w $2894, $B00,$14F3  ; DATA XREF: ROM:off_3E16C   o
                dc.w $A884, $F00,$F4F3
word_EBAB0:     dc.w $A123, $F00,$EFF1  ; DATA XREF: ROM:00034C64   o
word_EBAB6:     dc.w $A117, $E00,$F3F2  ; DATA XREF: ROM:00034C64   o
word_EBABC:     dc.w $A107, $F00,$F0F1  ; DATA XREF: ROM:00034C64   o
word_EBAC2:     dc.w $A0FB, $B00,$F2F4  ; DATA XREF: ROM:00034C64   o
word_EBAC8:     dc.w $A933, $F00,$EFF0  ; DATA XREF: ROM:00034C64   o
word_EBACE:     dc.w $A8FB, $B00,$F1F4  ; DATA XREF: ROM:00034C64   o
word_EBAD4:     dc.w $A907, $F00,$EFF0  ; DATA XREF: ROM:00034C64   o
word_EBADA:     dc.w $A917, $E00,$F3EE  ; DATA XREF: ROM:00034C64   o
                dc.w $20EF, $B00,$F0E8
                dc.w $A8EF, $B00,$F000
word_EBAEC:     dc.w $A167, $B00,$EDED  ; DATA XREF: ROM:00034C64   o
word_EBAF2:     dc.w $A15B, $B00,$EEEC  ; DATA XREF: ROM:00034C64   o
word_EBAF8:     dc.w $A14F, $E00,$F7E8  ; DATA XREF: ROM:00034C64   o
word_EBAFE:     dc.w $A143, $E00,$F8E9  ; DATA XREF: ROM:00034C64   o
word_EBB04:     dc.w $A197, $E00,$FAEC  ; DATA XREF: ROM:00034C64   o
word_EBB0A:     dc.w $B98B, $E00,$FBEE  ; DATA XREF: ROM:00034C64   o
word_EBB10:     dc.w $B97F, $B00,$F8F7  ; DATA XREF: ROM:00034C64   o
word_EBB16:     dc.w $B973, $B00,$F7F7  ; DATA XREF: ROM:00034C64   o
word_EBB1C:     dc.w $28A0, $E00,$F613  ; DATA XREF: ROM:off_3E16C   o
                dc.w $A8AC, $F00,$EEF3
word_EBB28:     dc.w $603C, $500, $105  ; DATA XREF: ROM:00034DB6   o
                dc.w $E034, $700,$EEF5
word_EBB34:     dc.w $7846, $500,$ECFB  ; DATA XREF: ROM:00034DB6   o
                dc.w $F840, $600,$FCF6
word_EBB40:     dc.w $7852, $400,$ECF8  ; DATA XREF: ROM:00034DB6   o
                dc.w $F84A, $700,$F4F8
word_EBB4C:     dc.w $605D, $500,$FE05  ; DATA XREF: ROM:00034DB6   o
                dc.w $E054, $A00,$F1ED
word_EBB58:     dc.w $786A, $900,$EBF8  ; DATA XREF: ROM:00034DB6   o
                dc.w $F861, $A00,$FBF3
word_EBB64:     dc.w $6074, $900,$F9FE  ; DATA XREF: ROM:00034DB6   o
                dc.w $E070, $500,$F3EE
word_EBB70:     dc.w $7882, $500, $3EE  ; DATA XREF: ROM:00034DB6   o
                dc.w $F87A, $D00,$F3F1
word_EBB7C:     dc.w $788E, $100,$F7EB  ; DATA XREF: ROM:00034DB6   o
                dc.w $F886, $D00,$F7F3
word_EBB88:     dc.w $E8C6, $400,$FBF8  ; DATA XREF: ROM:00034DB6   o
word_EBB8E:     dc.w $E8C8, $400,$FCF8  ; DATA XREF: ROM:00034DB6   o
word_EBB94:     dc.w $E8CA, $500,$FAFA  ; DATA XREF: ROM:00034DB6   o
word_EBB9A:     dc.w $E8CE, $100,$F9FD  ; DATA XREF: ROM:00034DB6   o
word_EBBA0:     dc.w $E8D0, $100,$F8FD  ; DATA XREF: ROM:00034DB6   o
word_EBBA6:     dc.w $F0AB, $100,$F8FC  ; DATA XREF: ROM:00034DB6   o
word_EBBAC:     dc.w $F0AD, $500,$F6FB  ; DATA XREF: ROM:00034DB6   o
word_EBBB2:     dc.w $F0B1, $400,$FBFA  ; DATA XREF: ROM:00034DB6   o
word_EBBB8:     dc.w $2866, $D00, $2FA  ; DATA XREF: sub_3C168+64   o sub_3C6F2+1C4   o ...
                dc.w $2864, $400,$EAFA
                dc.w $A85C, $D00,$F2FA
word_EBBCA:     dc.w $286E, $D00, $2FA  ; DATA XREF: sub_3C6F2+152   o sub_3CA3C+18   o
                dc.w $2864, $400,$EAFA
                dc.w $A85C, $D00,$F2FA
word_EBBDC:     dc.w $A0C5, $D00,$F8F0  ; DATA XREF: ROM:00034F20   o
word_EBBE2:     dc.w $A0BD, $D00,$F8F1  ; DATA XREF: ROM:00034F20   o
word_EBBE8:     dc.w $A0B4, $A00,$F5F3  ; DATA XREF: ROM:00034F20   o
word_EBBEE:     dc.w $A0A8, $B00,$F2F6  ; DATA XREF: ROM:00034F20   o
word_EBBF4:     dc.w $A0A0, $700,$F1F8  ; DATA XREF: ROM:00034F20   o
word_EBBFA:     dc.w $A8A8, $B00,$F2F2  ; DATA XREF: ROM:00034F20   o
word_EBC00:     dc.w $A8B4, $A00,$F4F5  ; DATA XREF: ROM:00034F20   o
word_EBC06:     dc.w $A8BD, $D00,$F8F0  ; DATA XREF: ROM:00034F20   o
word_EBC0C:     dc.w $287E, $100,$FBF2  ; DATA XREF: sub_3C6F2+1CC   o sub_3C9C0   o
                dc.w $A876, $D00,$FBFA
word_EBC18:     dc.w $28D6, $200,$FBF3  ; DATA XREF: sub_3C55C+26   o sub_3C55C+2E   o ...
                dc.w $A8CE, $700,$FBFB
word_EBC24:     dc.w $E856, $500,$F9F8  ; DATA XREF: ROM:00034F8A   o
word_EBC2A:     dc.w $E85A, $500,$F9F8  ; DATA XREF: ROM:00034F8A   o
word_EBC30:     dc.w $E85E, $500,$F9F8  ; DATA XREF: ROM:00034F8A   o
word_EBC36:     dc.w $E862, $500,$F9F8  ; DATA XREF: ROM:00034F8A   o
word_EBC3C:     dc.w $F046, $500,$F8FA  ; DATA XREF: ROM:00034F8A   o
word_EBC42:     dc.w $F04A, $500,$F9FA  ; DATA XREF: ROM:00034F8A   o
word_EBC48:     dc.w $F04E, $500,$F9F9  ; DATA XREF: ROM:00034F8A   o
word_EBC4E:     dc.w $F052, $500,$F9F9  ; DATA XREF: ROM:00034F8A   o
word_EBC54:     dc.w $E093, $D00,$F8EF  ; DATA XREF: ROM:00034F8A   o
word_EBC5A:     dc.w $E08B, $D00,$F7ED  ; DATA XREF: ROM:00034F8A   o
word_EBC60:     dc.w $E082, $A00,$F3F5  ; DATA XREF: ROM:00034F8A   o
word_EBC66:     dc.w $E07A, $700,$F2F9  ; DATA XREF: ROM:00034F8A   o
word_EBC6C:     dc.w $E872, $700,$F0F8  ; DATA XREF: ROM:00034F8A   o
word_EBC72:     dc.w $E87A, $700,$F2F8  ; DATA XREF: ROM:00034F8A   o
word_EBC78:     dc.w $E882, $A00,$F3F4  ; DATA XREF: ROM:00034F8A   o
word_EBC7E:     dc.w $E88B, $D00,$F7F3  ; DATA XREF: ROM:00034F8A   o
word_EBC84:     dc.w $E09B, $D00,$FCE8  ; DATA XREF: ROM:00034F8A   o
word_EBC8A:     dc.w $60D8,    0,    5  ; DATA XREF: ROM:00034F8A   o
                dc.w $60D7,    0,$F8FD
                dc.w $E0D1, $900,  $ED
word_EBC9C:     dc.w $60D0,    0,$FC04  ; DATA XREF: ROM:00034F8A   o
                dc.w $E0CA, $600,$FCF4
word_EBCA8:     dc.w $E0C2, $700,$F8FC  ; DATA XREF: ROM:00034F8A   o
word_EBCAE:     dc.w $F8BA, $700,$F8FE  ; DATA XREF: ROM:00034F8A   o
word_EBCB4:     dc.w $78B9,    0,$F301  ; DATA XREF: ROM:00034F8A   o
                dc.w $78B8,    0,$FBF9
                dc.w $F8B2, $600,$FB01
word_EBCC6:     dc.w $78B1,    0,$F4FE  ; DATA XREF: ROM:00034F8A   o
                dc.w $F8AB, $900,$FCFE
word_EBCD2:     dc.w $F8A3, $D00,$F4F8  ; DATA XREF: ROM:00034F8A   o
word_EBCD8:     dc.w  $814, $100,$D8FD  ; DATA XREF: ROM:off_2F194   o
                dc.w  $804,    0,$E820
                dc.w  $822, $C00,$18F0
                dc.w  $816, $B00,$F8F0
                dc.w  $805,    0,$F008
                dc.w  $80B, $A00,$E0F0
                dc.w $8800, $C00,$E008
word_EBD02:     dc.w  $814, $100,$D8FC  ; DATA XREF: ROM:off_2F194   o
                dc.w  $805,    0,$F008
                dc.w  $822, $C00,$18F0
                dc.w  $816, $B00,$F8F0
                dc.w  $85F,    0,$F018
                dc.w  $835,    0,$E008
                dc.w  $85C, $800,$E808
                dc.w $880B, $A00,$E0F0
word_EBD32:     dc.w  $814, $100,$D8FB  ; DATA XREF: sub_2EF4E+22   o sub_2EFEA+A   o ...
                dc.w  $822, $C00,$18F0
                dc.w  $816, $B00,$F8F0
                dc.w  $806, $100,$F010
                dc.w  $808, $200,$E008
                dc.w $880B, $A00,$E0F0
                dc.w $8814, $100,$FAFC
word_EBD5C:     dc.w  $86C, $100,$100C  ; DATA XREF: sub_2EFC8+A   o sub_2F0F6+24   o
                dc.w  $860, $B00,  $F4
                dc.w  $833, $100,$F0E4
                dc.w  $826,    0,$E0FC
                dc.w $8827, $E00,$E8EC
word_EBD7A:     dc.w  $858, $500,$10EE  ; DATA XREF: sub_2F01A+6   o sub_2F0CA+1E   o
                dc.w  $856, $400,$1006
                dc.w  $850, $900,  $E6
                dc.w  $848, $D00,  $FE
                dc.w  $842, $600,$E8E6
                dc.w $8836, $E00,$E8F6
word_EBD9E:     dc.w $A841, $D00,$F8F0  ; DATA XREF: ROM:00041548   o
word_EBDA4:     dc.w $B86D, $E00,$F3F1  ; DATA XREF: ROM:00041548   o
word_EBDAA:     dc.w $B851, $F00,$EFF0  ; DATA XREF: ROM:00041548   o
word_EBDB0:     dc.w $B861, $B00,$EFF5  ; DATA XREF: ROM:00041548   o
word_EBDB6:     dc.w $B849, $700,$EFF8  ; DATA XREF: ROM:00041548   o
word_EBDBC:     dc.w $B061, $B00,$EFF4  ; DATA XREF: ROM:00041548   o
word_EBDC2:     dc.w $B051, $F00,$EFF1  ; DATA XREF: ROM:00041548   o
word_EBDC8:     dc.w $B06D, $E00,$F2EF  ; DATA XREF: ROM:00041548   o
word_EBDCE:     dc.w $8040, $F00,$EDED  ; DATA XREF: ROM:0003EFAE   o
word_EBDD4:     dc.w $9860, $F00,$F0EF  ; DATA XREF: ROM:0003EFAE   o
word_EBDDA:     dc.w $187C, $200,$F309  ; DATA XREF: ROM:0003EFAE   o
                dc.w $9870, $B00,$F3F1
word_EBDE6:     dc.w $9850, $F00,$F2F2  ; DATA XREF: ROM:0003EFAE   o
                dc.w $8900, $A00,$F2F4
                dc.w $8909, $700,$F1FA
                dc.w $90EF, $A00,$F4F3
                dc.w $90F8, $D00,$F7F1
word_EBE04:     dc.w $8000, $F00,$EDF1  ; DATA XREF: ROM:0003EFBE   o
word_EBE0A:     dc.w $9830, $F00,$EEF2  ; DATA XREF: ROM:0003EFBE   o
word_EBE10:     dc.w $9820, $F00,$EFEF  ; DATA XREF: ROM:0003EFBE   o
word_EBE16:     dc.w $9810, $F00,$EFF0  ; DATA XREF: ROM:0003EFBE   o
                dc.w  $8C2,    0,$FFE5
                dc.w $88BA, $D00,$F7ED
                dc.w  $8CB, $200, $2F0
                dc.w $88C3, $700,$F2F8
                dc.w  $8D6,    0,$1401
                dc.w $88CE, $700,$F4F9
                dc.w $10B8, $400, $80A
                dc.w $90B0, $D00,$F8F3
word_EBE4C:     dc.w $988B, $900,$F7F3  ; DATA XREF: ROM:0003EFCE   o ROM:0003EFDE   o
word_EBE52:     dc.w $987F, $600,$F6F9  ; DATA XREF: ROM:0003EFCE   o ROM:0003EFDE   o
word_EBE58:     dc.w $8085, $600,$F7F9  ; DATA XREF: ROM:0003EFCE   o ROM:0003EFDE   o
word_EBE5E:     dc.w $8091, $900,$F8F8  ; DATA XREF: ROM:0003EFCE   o ROM:0003EFDE   o
                dc.w $88D7, $900,$F9F2
                dc.w $88DD, $600,$F6FC
                dc.w $88E3, $600,$F7FB
                dc.w $88E9, $900,$F4F8
                dc.w $18A8, $D00,  $F0
                dc.w $88A8, $D00,$F0F0
word_EBE88:     dc.w $5849, $D00,  $F0  ; DATA XREF: ROM:000425AA   o
                dc.w $C849, $D00,$F0F0
word_EBE94:     dc.w $4038, $700,$F0F0  ; DATA XREF: sub_32708+66   o sub_328C0+A6   o ...
                dc.w $C838, $700,$F000
word_EBEA0:     dc.w $C840, $A00,$F3F3  ; DATA XREF: sub_32836+62   o sub_41AAA+160   o
word_EBEA6:     dc.w $1810, $400,$ECF8  ; DATA XREF: ROM:off_432FA   o
                dc.w $9800, $F00,$F4F0
word_EBEB2:     dc.w $1022, $400,$EDF6  ; DATA XREF: ROM:off_432FA   o
                dc.w $9012, $F00,$F5EF
word_EBEBE:     dc.w $9024, $F00,$F2F1  ; DATA XREF: ROM:off_432FA   o
word_EBEC4:     dc.w $1044, $100,$F7EB  ; DATA XREF: ROM:off_432FA   o
                dc.w $9034, $F00,$F0F3
word_EBED0:     dc.w  $84E, $100,$F70D  ; DATA XREF: ROM:off_432FA   o
                dc.w $1846, $D00,$FFED
                dc.w $8846, $D00,$EFED
word_EBEE2:     dc.w $1844, $100,$F60D  ; DATA XREF: ROM:off_432FA   o
                dc.w $9834, $F00,$EFED
word_EBEEE:     dc.w $9824, $F00,$F1EF  ; DATA XREF: ROM:off_432FA   o
word_EBEF4:     dc.w $1822, $400,$ECFA  ; DATA XREF: ROM:off_432FA   o
                dc.w $9812, $F00,$F4F1
word_EBF00:     dc.w $8865, $800,$FCF4  ; DATA XREF: ROM:off_4331A   o
word_EBF06:     dc.w $985F, $900,$F4F3  ; DATA XREF: ROM:off_4331A   o
word_EBF0C:     dc.w $1859, $100,$FEF8  ; DATA XREF: ROM:off_4331A   o
                dc.w $985B, $500,$F600
word_EBF18:     dc.w $9853, $600,$F4FB  ; DATA XREF: ROM:off_4331A   o
word_EBF1E:     dc.w $9850, $200,$F4FC  ; DATA XREF: ROM:off_4331A   o
word_EBF24:     dc.w $9053, $600,$F4F5  ; DATA XREF: ROM:off_4331A   o
word_EBF2A:     dc.w $1059, $100,$FF01  ; DATA XREF: ROM:off_4331A   o
                dc.w $905B, $500,$F7F1
word_EBF36:     dc.w $905F, $900,$F5F6  ; DATA XREF: ROM:off_4331A   o
                dc.w $986E, $400,$FBF6
                dc.w $986C, $400,$FCF6
                dc.w $986A, $400,$FCF4
                dc.w $9868, $100,$F9FB
                dc.w $8070, $100,$F9FC
                dc.w $9068, $100,$F9FC
                dc.w $906A, $400,$FCFB
                dc.w $906C, $400,$FCFA
word_EBF6C:     dc.w   $BB, $D00,$FFE0  ; DATA XREF: ROM:off_43892   o
                dc.w $88BB, $D00,$FF00
word_EBF78:     dc.w   $C3, $D00,$FFE0  ; DATA XREF: ROM:off_43892   o
                dc.w $88C3, $D00,$FF00
word_EBF84:     dc.w   $CB, $D00,$FFE0  ; DATA XREF: ROM:off_43892   o sub_438AE+6   o
                dc.w $88CB, $D00,$FF00
word_EBF90:     dc.w  $8D3, $A00,$F6F4  ; DATA XREF: ROM:stru_EBFC0   o
                dc.w $88DF, $800, $8F4
word_EBF9C:     dc.w  $8D3, $A00,$F8F4  ; DATA XREF: ROM:stru_EBFC0   o ROM:stru_EBFCC   o
                dc.w $88DC, $800, $8F4
word_EBFA8:     dc.w  $8D3, $A00,$F7F4  ; DATA XREF: ROM:stru_EBFCC   o
                dc.w $88DC, $800, $8F4
word_EBFB4:     dc.w  $8D3, $A00,$F6F4  ; DATA XREF: ROM:stru_EBFCC   o
                dc.w $88DC, $800, $8F4
stru_EBFC0:     dc.w word_EBF90-*       ; field_0 ; DATA XREF: ROM:0004393C   o ROM:stru_EBFC0   o ...
                dc.w     5              ; field_2
                dc.w word_EBF9C-*       ; field_0
                dc.w     5              ; field_2
                dc.w stru_EBFC0-*       ; field_0
                dc.w     0              ; field_2
stru_EBFCC:     dc.w word_EBF9C-*       ; field_0 ; DATA XREF: ROM:00043940   o sub_43956+1A   o ...
                dc.w     8              ; field_2
                dc.w word_EBFA8-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_EBFB4-*       ; field_0
                dc.w     8              ; field_2
                dc.w word_EBFA8-*       ; field_0
                dc.w     3              ; field_2
                dc.w stru_EBFCC-*       ; field_0
                dc.w     0              ; field_2
word_EBFE0:     dc.w $6828, $500,$11F8  ; DATA XREF: ROM:off_3F198   o
                dc.w $6800, $D00,$E2F0
                dc.w $681C, $B00,$F2E8
                dc.w $E810, $B00,$F200
word_EBFF8:     dc.w $6808, $D00,$E2F0  ; DATA XREF: ROM:off_3F198   o sub_3F2D0+78   o
                dc.w $6828, $500,$11F8
                dc.w $681C, $B00,$F2E8
                dc.w $E810, $B00,$F200
word_EC010:     dc.w $E82C, $F00,$F0F0  ; DATA XREF: ROM:off_4054A   o
word_EC016:     dc.w $E83C, $F00,$F1EF  ; DATA XREF: ROM:off_4054A   o
word_EC01C:     dc.w $E84C, $F00,$F2EE  ; DATA XREF: ROM:off_4054A   o
word_EC022:     dc.w $E85C, $F00,$F3EE  ; DATA XREF: sub_3F2D0+A2   o ROM:off_4054A   o
word_EC028:     dc.w $E86C, $A00,$F4F5  ; DATA XREF: ROM:off_4054A   o
word_EC02E:     dc.w $E875, $A00,$F5F4  ; DATA XREF: ROM:off_4054A   o
word_EC034:     dc.w $E87E, $A00,$F6F3  ; DATA XREF: ROM:off_4054A   o
                dc.w $2808, $700,  $F8
                dc.w $A800, $700,$E0F8
word_EC046:     dc.w $2018, $B00,$EFE8  ; DATA XREF: sub_45D9A+AE   o sub_46BF2+6   o ...
                dc.w $2818, $B00,$EF00
                dc.w $2024, $100,$DFF0
                dc.w $A824, $100,$DF08
word_EC05E:     dc.w $2026, $B00,$F0E8  ; DATA XREF: sub_46B8A:loc_46BAA   o sub_46B8A:loc_46BD2   o
                dc.w $2826, $B00,$F000
                dc.w $2024, $100,$E0F0
                dc.w $2824, $100,$E008
                dc.w $2032,    0,$10F8
                dc.w $A832,    0,$1000
word_EC082:     dc.w $2843, $100, $2F4  ; DATA XREF: sub_45D9A+11E   o sub_45D9A+16C   o
                dc.w $A833, $F00,$F2FC
word_EC08E:     dc.w $2008, $A00, $1E8  ; DATA XREF: ROM:off_4890A   o
                dc.w $2808, $A00, $100
                dc.w $2000, $700,$E1F0
                dc.w $A800, $700,$E100
word_EC0A6:     dc.w $201D, $900, $8E8  ; DATA XREF: ROM:off_4890A   o
                dc.w $281D, $900, $800
                dc.w $2011, $B00,$E8E8
                dc.w $A811, $B00,$E800
word_EC0BE:     dc.w $2023, $B00,$ECEC  ; DATA XREF: ROM:off_4890A   o
                dc.w $202F, $800, $CEC
                dc.w $282F, $800, $CFC
                dc.w $A823, $B00,$ECFC
word_EC0D6:     dc.w $2032, $700,$F0F0  ; DATA XREF: ROM:off_4890A   o
                dc.w $A832, $700,$F000
word_EC0E2:     dc.w $203A, $600,$F4F4  ; DATA XREF: ROM:off_4890A   o
                dc.w $A83A, $600,$F4FC
word_EC0EE:     dc.w $204E, $100,$18F5  ; DATA XREF: ROM:off_4890A   o
                dc.w $204C, $400,$10ED
                dc.w $284E, $100,$1805
                dc.w $284C, $400,$1005
                dc.w $2040, $B00,$F0ED
                dc.w $A840, $B00,$F0FD
word_EC112:     dc.w $3850, $D00,  $E3  ; DATA XREF: ROM:off_48922   o
                dc.w $3858, $A00,    3
                dc.w $2858, $A00,$E803
                dc.w $A850, $D00,$F0E3
word_EC12A:     dc.w $386D, $600,  $E8  ; DATA XREF: ROM:off_48922   o
                dc.w $3861, $E00,  $F8
                dc.w $286D, $600,$E8E8
                dc.w $A861, $E00,$E8F8
word_EC142:     dc.w $387F, $200,$FCEC  ; DATA XREF: ROM:off_48922   o
                dc.w $287F, $200,$ECEC
                dc.w $3873, $E00,$FCF4
                dc.w $A873, $E00,$ECF4
word_EC15A:     dc.w $3882, $D00,  $F0  ; DATA XREF: ROM:off_48922   o
                dc.w $A882, $D00,$F0F0
word_EC166:     dc.w $388A, $900,$FCF4  ; DATA XREF: ROM:off_48922   o
                dc.w $A88A, $900,$F4F4
word_EC172:     dc.w $38B6, $400, $418  ; DATA XREF: ROM:off_48922   o
                dc.w $28B6, $400,$F418
                dc.w $38B4, $100, $410
                dc.w $28B4, $100,$EC10
                dc.w $38A8, $E00,$FCF0
                dc.w $A8A8, $E00,$ECF0
word_EC196:     dc.w $38B8, $D00,  $F4  ; DATA XREF: ROM:off_48846   o
                dc.w $38C0, $C00,  $D4
                dc.w $38C4, $800,  $BC
                dc.w $28C4, $800,$F8BC
                dc.w $28C0, $C00,$F8D4
                dc.w $A8B8, $D00,$F0F4
word_EC1BA:     dc.w $30D3, $200,$2EF8  ; DATA XREF: ROM:off_48846   o
                dc.w $38D3, $200,$2E00
                dc.w $30CF, $300, $EF8
                dc.w $38CF, $300, $E00
                dc.w $30C7, $700,$EEF0
                dc.w $B8C7, $700,$EE00
word_EC1DE:     dc.w $30F1, $D00,$EAEA  ; DATA XREF: ROM:off_48846   o
                dc.w $30F0,    0, $A12
                dc.w $30E4, $E00,$FAF2
                dc.w $30DC, $D00,$120A
                dc.w $B0D6, $900,$221A
                dc.w $A910, $400,$FCF8
                dc.w $B90E, $400,$FCF8
                dc.w $B90A, $500,$F8F8
                dc.w $A108, $100,$F8FC
                dc.w $A906, $100,$F8FC
word_EC21A:     dc.w $38F1, $D00,$EAF6  ; DATA XREF: ROM:off_48846   o
                dc.w $38F0,    0, $AE6
                dc.w $38E4, $E00,$FAEE
                dc.w $38DC, $D00,$12D6
                dc.w $B8D6, $900,$22CE
word_EC238:     dc.w     0, $100,$F8F8  ; DATA XREF: sub_492F4+136   o ROM:off_494FE   o ...
                dc.w $8800, $100,$F800
word_EC244:     dc.w     2, $100,$F8F8  ; DATA XREF: sub_492F4+3A   o sub_492F4+8A   o
                dc.w $8802, $100,$F800
word_EC250:     dc.w     4, $700,$F0F0  ; DATA XREF: ROM:off_494FE   o
                dc.w $8804, $700,$F000
word_EC25C:     dc.w    $D, $700,$F0F0  ; DATA XREF: sub_492F4+12   o sub_492F4+62   o ...
                dc.w $880D, $700,$F000
word_EC268:     dc.w   $15, $700,$F0F0  ; DATA XREF: ROM:off_4A4F4   o
                dc.w $8815, $700,$F000
word_EC274:     dc.w   $1D, $700,$F0F0  ; DATA XREF: ROM:off_4A4F4   o
                dc.w $881D, $700,$F000
word_EC280:     dc.w   $25, $700,$F0F0  ; DATA XREF: ROM:off_4A4F4   o
                dc.w $8825, $700,$F000
word_EC28C:     dc.w $880C,    0,$FCFC  ; DATA XREF: ROM:off_494FE   o
word_EC292:     dc.w   $7F, $600,$F420  ; DATA XREF: sub_4B540+3A   o
                dc.w  $873, $E00,$F400
                dc.w  $87F, $600,$F4D0
                dc.w $8873, $E00,$F4E0
word_EC2AA:     dc.w  $855, $800, $CEF  ; DATA XREF: sub_4A938+160   o sub_4B6AC+6   o
                dc.w $8845, $F00,$ECEF
word_EC2B6:     dc.w  $86B, $D00, $CEF  ; DATA XREF: sub_4B524+8   o
                dc.w  $868, $800,$E4EF
                dc.w $8858, $F00,$ECEF
word_EC2C8:     dc.w $8885, $300,$EFFC  ; DATA XREF: ROM:off_4BD6C   o
word_EC2CE:     dc.w $8889, $B00,$EFF3  ; DATA XREF: ROM:off_4BD6C   o
word_EC2D4:     dc.w $8895, $F00,$EFF0  ; DATA XREF: sub_4A938+1C0   o sub_4B1AC+48   o ...
word_EC2DA:     dc.w $88A5, $B00,$EFF5  ; DATA XREF: ROM:off_4BD6C   o
word_EC2E0:     dc.w $88B1, $F00,$EFF0  ; DATA XREF: ROM:off_4BD6C   o
word_EC2E6:     dc.w $7836, $E00,  $F8  ; DATA XREF: ROM:off_45012   o
                dc.w $7842, $600,  $E8
                dc.w $6842, $600,$E8E8
                dc.w $E836, $E00,$E8F8
word_EC2FE:     dc.w $6868, $500, $8E8  ; DATA XREF: ROM:off_45012   o
                dc.w $6860, $D00, $8F8
                dc.w $6858, $700,$E8E8
                dc.w $E848, $F00,$E8F8
word_EC316:     dc.w $700C, $900,$E8E8  ; DATA XREF: ROM:off_45012   o
                dc.w $7000, $B00,$F8E8
                dc.w $780C, $900,$E800
                dc.w $F800, $B00,$F800
word_EC32E:     dc.w $7032, $500,$E808  ; DATA XREF: ROM:off_45012   o
                dc.w $702A, $D00,$E8E8
                dc.w $7022, $700,$F808
                dc.w $F012, $F00,$F8E8
word_EC346:     dc.w $7887, $D00,  $F0  ; DATA XREF: ROM:off_45012   o
                dc.w $E887, $D00,$F0F0
word_EC352:     dc.w $689E, $500,$FEF2  ; DATA XREF: ROM:off_45012   o
                dc.w $6898, $600,$E6F2
                dc.w $688F,    0,$FE12
                dc.w $E890, $700,$EE02
word_EC36A:     dc.w $706C, $700,$F0F0  ; DATA XREF: ROM:off_45012   o
                dc.w $F86C, $700,$F000
word_EC376:     dc.w $7086,    0,$E6FE  ; DATA XREF: ROM:off_45012   o
                dc.w $707E, $D00,$EEEE
                dc.w $707A, $500,$FEFE
                dc.w $F074, $900,$FEE6
word_EC38E:     dc.w $E8A2, $800,$FCF4  ; DATA XREF: ROM:000350E6   o
word_EC394:     dc.w $E8A5, $900,$F8F4  ; DATA XREF: ROM:000350E6   o
word_EC39A:     dc.w $68AF, $400, $2F4  ; DATA XREF: ROM:000350E6   o
                dc.w $E8AB, $500,$F2FC
word_EC3A6:     dc.w $E8B1, $600,$F5FA  ; DATA XREF: ROM:000350E6   o
word_EC3AC:     dc.w $E8B7, $200,$F5FC  ; DATA XREF: ROM:000350E6   o
word_EC3B2:     dc.w $E0B1, $600,$F5F8  ; DATA XREF: ROM:000350E6   o
word_EC3B8:     dc.w $60AF, $400, $3FE  ; DATA XREF: ROM:000350E6   o
                dc.w $E0AB, $500,$F3F6
word_EC3C4:     dc.w $E0A5, $900,$F8F5  ; DATA XREF: ROM:000350E6   o
                dc.w $E0A2, $800,$FCF5
word_EC3D0:     dc.w $E8BA, $800,$FCF4  ; DATA XREF: ROM:000350E6   o
word_EC3D6:     dc.w $E8BD, $900,$F8F3  ; DATA XREF: ROM:000350E6   o
word_EC3DC:     dc.w $E8C3, $A00,$F4F4  ; DATA XREF: ROM:000350E6   o
word_EC3E2:     dc.w $E8CC, $600,$F3F9  ; DATA XREF: ROM:000350E6   o
word_EC3E8:     dc.w $E8D2, $200,$F4FC  ; DATA XREF: ROM:000350E6   o
word_EC3EE:     dc.w $E0CC, $600,$F3F7  ; DATA XREF: ROM:000350E6   o
word_EC3F4:     dc.w $E0C3, $A00,$F4F4  ; DATA XREF: ROM:000350E6   o
word_EC3FA:     dc.w $E0BD, $900,$F8F4  ; DATA XREF: ROM:000350E6   o
                dc.w $E8BA, $800,$FCF4
word_EC406:     dc.w $E8D5, $A00,$F4F3  ; DATA XREF: sub_456EC+46   o
                dc.w $E0D5, $A00,$F4F6
word_EC412:     dc.w $E8EF, $F00,$F0F0  ; DATA XREF: sub_458F6+12   o ROM:stru_EC42A   o
word_EC418:     dc.w $E8FF, $A00,$F4F4  ; DATA XREF: ROM:stru_EC42A   o
word_EC41E:     dc.w $E908, $500,$F8F8  ; DATA XREF: ROM:stru_EC42A   o
word_EC424:     dc.w $E90C,    0,$FCFC  ; DATA XREF: ROM:stru_EC42A   o
stru_EC42A:     dc.w word_EC412-*       ; field_0 ; DATA XREF: update_ent_CA+100   o ROM:stru_EC42A   o ...
                dc.w     3              ; field_2
                dc.w word_EC418-*       ; field_0
                dc.w     3              ; field_2
                dc.w word_EC41E-*       ; field_0
                dc.w     2              ; field_2
                dc.w word_EC424-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_EC424-*       ; field_0
                dc.w   $FF              ; field_2
                dc.w $4858,    0, $5FE
                dc.w $4856, $400,$FDF6
                dc.w $C853, $800,$F5EE
                dc.w $4867,    0, $C00
                dc.w $485F, $700,$ECF0
                dc.w $C859, $600,$F400
                dc.w $4871, $400, $6F8
                dc.w $4870,    0,$FDE8
                dc.w $C868, $D00,$F6F0
                dc.w $4873, $400,$F0F3
                dc.w $487E, $400, $8F9
                dc.w $487D,    0,$F8E9
                dc.w $C875, $D00,$F8F1
                dc.w $C880, $500,$F8F8
                dc.w $C884,    0,$FCFC
                dc.w $C885, $500,$F8F8
                dc.w $C889, $D00,$F8ED
                dc.w $C891, $D00,$F8ED
                dc.w $C899, $A00,$F4F4
                dc.w $C8A2, $700,$F2F8
                dc.w $C8AA, $700,$F2F8
                dc.w $C0A2, $700,$F2F9
                dc.w $C099, $A00,$F4F5
                dc.w $C091, $D00,$F8F4
                dc.w $C8B2, $E00,$F5F0
                dc.w $C8BE, $E00,$F2F0
                dc.w $48D5, $400, $AF6
                dc.w $48D3, $100,$FAEE
                dc.w $C8CA, $A00,$F2F6
                dc.w $C8D7, $B00,$F0F6
                dc.w $C8E3, $B00,$F0F2
                dc.w $C0D7, $B00,$F0F3
                dc.w $40D5, $400, $AFB
                dc.w $40D3, $100,$FA0B
                dc.w $C0CA, $A00,$F2F3
                dc.w $C0BE, $E00,$F2F1
                dc.w $C8EF, $D00,$F7F0
                dc.w $48FF, $400, $7F2
                dc.w $C8F7, $D00,$F7F2
                dc.w $4909,    0, $CF7
                dc.w $4901, $100,$F407
                dc.w $C903, $600,$F4F7
                dc.w $C90A, $700,$F1F8
                dc.w $C912, $700,$F0F8
                dc.w $4922, $100,$FE07
                dc.w $C91A, $700,$EEF7
                dc.w $4929, $C00, $1F4
                dc.w $4926, $800,$F9F4
                dc.w $C924, $400,$F1F4
                dc.w $C92D, $D00,$F8F1
                dc.w $C935, $C00,$FCF0
                dc.w $493C, $400, $2F3
                dc.w $C939, $800,$FAF7
                dc.w $493E,    0,$F706
                dc.w $C93F, $600,$F7F6
                dc.w $4949, $100, $3FB
                dc.w $C945, $500,$F3FB
                dc.w $C94B, $300,$EFFC
                dc.w $494F, $200,$F0FA
                dc.w $C952, $100,$FC02
                dc.w $4958, $800, $1F7
                dc.w $C954, $500,$F1F7
                dc.w $495E, $C00,$FDF0
                dc.w $C95B, $800,$F5F0
                dc.w $6885, $500,$2000
                dc.w $687D, $700,    0
                dc.w $687B, $100,$F000
                dc.w $E875, $600,$D8F8
                dc.w $6892, $100,$20FC
                dc.w $688E, $300,  $FC
                dc.w $688C, $100,$F0FC
                dc.w $E889, $200,$D8FC
                dc.w $6085, $500,$20F0
                dc.w $607D, $700,  $F0
                dc.w $607B, $100,$F0F8
                dc.w $E075, $600,$D8F8
                dc.w $6885, $500,$10FE
                dc.w $687D, $700,$F0FE
                dc.w $E875, $600,$D8F8
                dc.w $6892, $100,$10FC
                dc.w $688E, $300,$F0FC
                dc.w $E889, $200,$D8FC
                dc.w $6085, $500,$10F2
                dc.w $607D, $700,$F0F2
                dc.w $E075, $600,$D8F8
                dc.w $689D, $F00,$F4F0
                dc.w $E894, $A00,$DCEE
                dc.w $68C5, $100,$F5EC
                dc.w $68B5, $F00,$F5F4
                dc.w $E8AD, $D00,$E5E5
                dc.w $68D7, $A00,$F8DE
                dc.w $E8C7, $F00,$F0F6
                dc.w $68F0, $A00, $8F3
                dc.w $E8E0, $F00,$E8F3
                dc.w $E8F9, $D00,$F8F0
                dc.w $6907, $500, $3FA
                dc.w $E901, $900,$F3FA
                dc.w $6913, $100,$FF09
                dc.w $E90B, $700,$EFF9
                dc.w $E915, $D00,$F8EE
                dc.w $E91D, $A00,$F7F3
                dc.w $E927, $A00,$F7F2
                dc.w $E930, $A00,$F7F2
                dc.w $E93A, $700,$F6F8
                dc.w $E130, $A00,$F7F8
                dc.w $E127, $A00,$F7F7
                dc.w $E11D, $A00,$F7F7
word_EC6C0:     dc.w $284D, $C00, $5F0  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
                dc.w $284B, $100,$F5F0
                dc.w $A843, $D00,$F5F8
word_EC6D2:     dc.w $285E, $400, $7FA  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
                dc.w $285A, $300,$F70A
                dc.w $A851, $A00,$EFF2
word_EC6E4:     dc.w $2862, $700,$F6FA  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
                dc.w $A860, $400,$EEFA
word_EC6F0:     dc.w $2870, $100,$FEF4  ; DATA XREF: sub_50FD0+D4   o
                dc.w $A86A, $600,$F6FC
word_EC6FC:     dc.w $A872, $500,$F8F8  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
word_EC702:     dc.w $A876, $500,$F8F8  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
word_EC708:     dc.w $A87A, $500,$F9F8  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
word_EC70E:     dc.w $A87E, $500,$F8F8  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
word_EC714:     dc.w $A882, $500,$F8F9  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
word_EC71A:     dc.w $A886, $500,$F8F9  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
word_EC720:     dc.w $A88A, $500,$F7F9  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
word_EC726:     dc.w $A88E, $500,$F7F8  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
word_EC72C:     dc.w $A892, $D00,$F7F0  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
word_EC732:     dc.w $A89A, $900,$F6F7  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
word_EC738:     dc.w $28A6, $100,$FBF5  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
                dc.w $A8A0, $600,$F3FD
word_EC744:     dc.w $A8A8, $600,$F1FA  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
word_EC74A:     dc.w $A8AE, $700,$F0F8  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
word_EC750:     dc.w $A0A8, $600,$F1F7  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
word_EC756:     dc.w $20A6, $100,$FB04  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
                dc.w $A0A0, $600,$F3F4
word_EC762:     dc.w $A09A, $900,$F6F3  ; DATA XREF: ROM:000353BC   o ROM:off_354B0   o
                dc.w $A8B6, $D00,$F8EF
                dc.w $A8BE, $D00,$F5F0
                dc.w $28CE, $400, $2F1
                dc.w $A8C6, $D00,$F2F1
                dc.w $28D6, $500, $1F5
                dc.w $A8D0, $900,$F1F6
                dc.w $A8DA, $700,$F1FB
word_EC792:     dc.w $A8E2, $700,$F0F7  ; DATA XREF: sub_50FD0+EE   o sub_50FD0+274   o
                dc.w $28EE, $900,$FFF4
                dc.w $A8EA, $500,$EFF4
                dc.w $28FA, $500,$FB02
                dc.w $A8F4, $600,$F2F2
                dc.w $290D, $500,$23EA
                dc.w $2907, $900,$13EA
                dc.w $A8FE, $A00,$FBF1
word_EC7C2:     dc.w $A911, $900,$F8FB  ; DATA XREF: sub_50FD0+68   o sub_50FD0+9C   o ...
word_EC7C8:     dc.w $A917, $900,$FBF8  ; DATA XREF: sub_50FD0+1D0   o sub_50FD0+20A   o
word_EC7CE:     dc.w $A91D, $500,$F8F2  ; DATA XREF: sub_50FD0+82   o sub_50FD0+B6   o
                dc.w $A921, $500,$F8F9
                dc.w $A925, $500,$F8F8
                dc.w $A929, $500,$F8F8
word_EC7E6:     dc.w $A8B6, $D00,$F3E4  ; DATA XREF: ROM:off_5139A   o
word_EC7EC:     dc.w $A8BE, $D00,$F4E2  ; DATA XREF: ROM:off_5139A   o
word_EC7F2:     dc.w $28CE, $400, $7E4  ; DATA XREF: ROM:off_5139A   o
                dc.w $A8C6, $D00,$F7E4
word_EC7FE:     dc.w $28D6, $500, $9EA  ; DATA XREF: ROM:off_5139A   o
                dc.w $A8D0, $900,$F9EB
word_EC80A:     dc.w $A8DA, $700,$FBF4  ; DATA XREF: ROM:off_5139A   o
word_EC810:     dc.w $A8E2, $700,$FCF5  ; DATA XREF: ROM:off_5139A   o
word_EC816:     dc.w $28EE, $900, $AF7  ; DATA XREF: ROM:off_5139A   o
                dc.w $A8EA, $500,$FAF7
word_EC822:     dc.w $28FA, $500, $509  ; DATA XREF: ROM:off_5139A   o
                dc.w $A8F4, $600,$FBF9
                dc.w $2941, $100,$F8E2
                dc.w $293D, $300,$E8EA
                dc.w $A92D, $F00,$E8F2
                dc.w $682A, $400, $9FD
                dc.w $6824, $600,$F1ED
                dc.w $E81C, $700,$E9FD
                dc.w $E82C, $C00,$FCE5
                dc.w $E830, $D00,$FBE6
                dc.w $E838, $A00,$FBED
                dc.w $E841, $700,$FAF5
                dc.w $E849, $300,$FBFE
                dc.w $E041, $700,$FAFD
                dc.w $E038, $A00,$FCFD
                dc.w $E030, $D00,$FCFC
                dc.w $E84D, $D00,$F8F0
                dc.w $6855, $800,$F2F9
                dc.w $E858, $D00,$FAF1
                dc.w $686A,    0, $4ED
                dc.w $6869,    0, $CF5
                dc.w $E860, $A00,$F4F5
                dc.w $6873, $200,$EF07
                dc.w $E86B, $700,$EFF7
                dc.w $E876, $700,$F0F8
                dc.w $6073, $200,$EFF1
                dc.w $E06B, $700,$EFF9
                dc.w $606A,    0, $30C
                dc.w $6069,    0, $B04
                dc.w $E060, $A00,$F3F4
                dc.w $6055, $800,$F1F0
                dc.w $E058, $D00,$F9F0
                dc.w $E882, $900,$F9ED
                dc.w $688E, $100,$FD08
                dc.w $E888, $600,$FCF8
                dc.w $E890, $600,$FBFB
                dc.w $689C, $400,$F1FF
                dc.w $E896, $900,$F9FE
                dc.w $E89E, $D00,$F8F0
                dc.w $68A6, $400,$F000
                dc.w $E8A8, $D00,$F8F0
                dc.w $E8B0, $A00,$F3F4
                dc.w $68B9, $100,$F008
                dc.w $E8BB, $700,$F0F8
                dc.w $E8C3, $700,$F0F9
                dc.w $60B9, $100,$F0F2
                dc.w $E0BB, $700,$F0FA
                dc.w $E0B0, $A00,$F4F6
                dc.w $60A6, $400,$F1F2
                dc.w $E0A8, $D00,$F9F2
                dc.w $E8CB, $D00,$F8F0
                dc.w $68DB, $400, $7F8
                dc.w $E8D3, $D00,$F7F0
                dc.w $E8DD, $A00,$F5F3
                dc.w $68EE, $100,$F9F2
                dc.w $E8E6, $700,$F1FA
                dc.w $E8F0, $700,$F1F8
                dc.w $60EE, $100,$F908
                dc.w $E0E6, $700,$F1F8
                dc.w $E0DD, $A00,$F5F5
                dc.w $60DB, $400, $7F9
                dc.w $E0D3, $D00,$F7F1
                dc.w $E8F8, $900,$F8F3
                dc.w $E8FE, $900,$F8F3
                dc.w $690A,    0, $7FB
                dc.w $E904, $900,$F7F3
                dc.w $6911,    0,$FDF1
                dc.w $E90B, $600,$F5F9
                dc.w $E912, $600,$F5F9
                dc.w $E918, $600,$F5F9
                dc.w $6924,    0,$FD08
                dc.w $E91E, $600,$F5F8
                dc.w $E925, $900,$F8F6
                dc.w $E869, $A00,$F4F4
                dc.w $E872, $A00,$F4F4
                dc.w $E87B, $A00,$F4F4
                dc.w $E884, $A00,$F4F4
                dc.w $E88D, $A00,$F4F4
                dc.w $E084, $A00,$F4F4
                dc.w $E07B, $A00,$F4F4
                dc.w $E072, $A00,$F4F4
                dc.w $E896, $A00,$F4F4
                dc.w $E89F, $A00,$F4F4
                dc.w $E8F0, $500,$F8F8
                dc.w $E8F4, $500,$F8F8
                dc.w $E8F8,    0,$FCFC
                dc.w $68C0,    0, $CEC
                dc.w $68B8, $300,$ECEC
                dc.w $68BC, $C00, $CF4
                dc.w $E8A8, $F00,$ECF4
                dc.w $E8C1, $A00,$F4F4
                dc.w $E8CA, $500,$F8F8
                dc.w $E8CE,    0,$FCFC
                dc.w $E8CF, $800,$FAF7
                dc.w $E8D2, $500,$FCF8
                dc.w $E8D6,    0,$FCFC
                dc.w $E8D7,    0,$FCFC
                dc.w $E8D8, $500,$F8F8
                dc.w $E8DC, $500,$F8F8
                dc.w $E8E0, $500,$F8F8
                dc.w $E8E4, $500,$F8F8
                dc.w $E8E8, $500,$F8F8
                dc.w $E8EC, $500,$F8F8
                dc.w $E8F9, $C00,$FCF0
                dc.w $68FF, $500,$FAF6
                dc.w $E8FD, $400,$FA06
                dc.w $6908,    0, $8F6
                dc.w $6906, $400,  $F6
                dc.w $E903, $800,$F8F6
                dc.w $690B, $300,$F5F9
                dc.w $E909, $100,$F501
                dc.w $E90F, $300,$F1FC
                dc.w $790B, $300,$ECFA
                dc.w $F909, $100,$FC02
                dc.w $7903, $800, $1F6
                dc.w $7906, $400,$F9F6
                dc.w $F908,    0,$F1F6
                dc.w $78FF, $500,$F6F5
                dc.w $F8FD, $400,$FE05
                dc.w $E913, $400,$FCF9
                dc.w $E915, $500,$F8F9
                dc.w $E919, $500,$F9F8
                dc.w $E91D, $500,$F8F9
                dc.w $E921, $100,$F8FC
                dc.w $E923, $500,$F8F9
                dc.w $E927, $500,$F9FA
                dc.w $E92B, $500,$F7F8
word_ECB1C:     dc.w $E8F2, $500,$F8F8  ; DATA XREF: ROM:off_4DA1A   o
word_ECB22:     dc.w $E8F6,    0,$FCFC  ; DATA XREF: ROM:off_4DA1A   o
word_ECB28:     dc.w $68FC, $600,$F0F0  ; DATA XREF: sub_4C954+62   o sub_4DB50+E   o ...
                dc.w $68F8, $500,$F000
                dc.w $E8F7,    0,$F010
word_ECB3A:     dc.w $6902, $500,$F000  ; DATA XREF: sub_4DB50:loc_4DB72   o
                dc.w $E8FC, $600,$F0F0
word_ECB46:     dc.w $E907,    0,$FCFC  ; DATA XREF: ROM:off_4CB2E   o
word_ECB4C:     dc.w $E906,    0,$FCFC  ; DATA XREF: ROM:off_4CB2E   o
word_ECB52:     dc.w $E908, $F00,$F0F0  ; DATA XREF: sub_4C954+22   o
word_ECB58:     dc.w $E918, $A00,$F4F4  ; DATA XREF: ROM:stru_4CB06   o
word_ECB5E:     dc.w $E921, $500,$F8F8  ; DATA XREF: ROM:stru_4CB06   o
word_ECB64:     dc.w $E925, $500,$F8F8  ; DATA XREF: ROM:stru_4CB06   o
word_ECB6A:     dc.w $78FC, $600,$F2F4  ; DATA XREF: sub_4C82C+4E   o
                dc.w $78F8, $500,$FA04
                dc.w $F8F7,    0, $214
word_ECB7C:     dc.w $692F, $500,  $F8  ; DATA XREF: sub_4C82C+2E   o
                dc.w $E929, $900,$F0F8
word_ECB88:     dc.w $6939,    0,$FCF3  ; DATA XREF: sub_4C43C+88   o sub_4C82C+3E   o
                dc.w $E933, $600,$F4FB
word_ECB94:     dc.w $E93A, $F00,$F0F0  ; DATA XREF: sub_4C43C+3E   o
word_ECB9A:     dc.w $E94A, $A00,$F4F4  ; DATA XREF: ROM:stru_4C5BE   o
word_ECBA0:     dc.w $E953, $500,$F8F8  ; DATA XREF: ROM:stru_4C5BE   o
word_ECBA6:     dc.w $E957, $500,$F8F8  ; DATA XREF: ROM:stru_4C5BE   o
word_ECBAC:     dc.w $E95B, $A00,$F4F4  ; DATA XREF: ROM:stru_ECBD0   o
word_ECBB2:     dc.w $E976, $500,$F8F8  ; DATA XREF: ROM:stru_ECBD0   o
word_ECBB8:     dc.w $E964, $A00,$F4F4  ; DATA XREF: ROM:stru_ECBDC   o
word_ECBBE:     dc.w $E96D, $A00,$F4F4  ; DATA XREF: ROM:stru_ECBDC   o
word_ECBC4:     dc.w $F164, $A00,$F4F4  ; DATA XREF: ROM:stru_ECBDC   o
word_ECBCA:     dc.w $F16D, $A00,$F4F4  ; DATA XREF: ROM:stru_ECBDC   o
stru_ECBD0:     dc.w word_ECBAC-*       ; field_0 ; DATA XREF: sub_4D568+A   o ROM:stru_ECBD0   o ...
                dc.w     2              ; field_2
                dc.w word_ECBB2-*       ; field_0
                dc.w     2              ; field_2
                dc.w stru_ECBD0-*       ; field_0
                dc.w     0              ; field_2
stru_ECBDC:     dc.w word_ECBB8-*       ; field_0 ; DATA XREF: sub_4D718+A   o ROM:stru_ECBDC   o ...
                dc.w     6              ; field_2
                dc.w word_ECBBE-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_ECBC4-*       ; field_0
                dc.w     6              ; field_2
                dc.w word_ECBCA-*       ; field_0
                dc.w     6              ; field_2
                dc.w stru_ECBDC-*       ; field_0
                dc.w     0              ; field_2
                dc.w $6909, $D00,  $F8
                dc.w $6889, $D00,$F0F8
                dc.w $E891, $200,$F0F0
                dc.w $6894, $D00,  $F8
                dc.w $6891, $200,$F0F0
                dc.w $E889, $D00,$F0F8
                dc.w $E89C, $E00,$F0F0
                dc.w $E8A8, $A00,$F4F3
                dc.w $E8B1, $600,$F4F8
                dc.w $E8B7, $A00,$F3F4
                dc.w $68D6, $C00, $2F6
                dc.w $E8D0, $900,$F2F6
                dc.w $68D6, $C00, $2F3
                dc.w $E8C8, $D00,$F2F3
                dc.w $68C0, $D00,$F2F1
                dc.w $E8D6, $C00, $2F1
                dc.w $68DA, $900, $2F3
                dc.w $E8C8, $D00,$F2F3
                dc.w $E8E0, $700,$F1F8
                dc.w $E8E8, $600,$F4F6
                dc.w $E8EE, $A00,$F4F4
                dc.w $E8F7, $A00,$F4F4
                dc.w $E900, $500,$F8F8
                dc.w $E904, $500,$F8F8
                dc.w $E908,    0,$FCFC
word_ECC86:     dc.w   $4E,    0,$FAE7  ; DATA XREF: ROM:off_59D42   o ROM:off_59D62   o
                dc.w $8042, $E00,$F2EF
word_ECC92:     dc.w $8036, $E00,$F2EF  ; DATA XREF: ROM:off_59D42   o ROM:off_59D62   o
word_ECC98:     dc.w   $35,    0, $BEF  ; DATA XREF: ROM:off_59D42   o ROM:off_59D62   o
                dc.w $8029, $E00,$F3EF
word_ECCA4:     dc.w $801D, $B00,$F2F6  ; DATA XREF: ROM:off_59D42   o ROM:off_59D62   o
word_ECCAA:     dc.w   $1C,    0,$11FC  ; DATA XREF: ROM:off_59D42   o ROM:off_59D62   o
                dc.w $8010, $B00,$F1F4
word_ECCB6:     dc.w $9868, $B00,$F1F4  ; DATA XREF: ROM:off_59D42   o ROM:off_59D62   o
word_ECCBC:     dc.w $1867,    0, $90D  ; DATA XREF: ROM:off_59D42   o ROM:off_59D62   o
                dc.w $985B, $B00,$F1F5
word_ECCC8:     dc.w $984F, $E00,$F3F3  ; DATA XREF: ROM:off_59D42   o ROM:off_59D62   o
                dc.w $184E,    0,$FD12
                dc.w $9842, $E00,$F5F2
word_ECCDA:     dc.w $8074, $A00,$F3F5  ; DATA XREF: ROM:off_59D62   o ROM:off_59DA2   o
word_ECCE0:     dc.w $98B5, $A00,$F2F4  ; DATA XREF: ROM:off_59D62   o ROM:off_59DA2   o
word_ECCE6:     dc.w $18B4,    0,$EBFC  ; DATA XREF: ROM:off_59D62   o ROM:off_59DA2   o
                dc.w $98AB, $A00,$F3F4
word_ECCF2:     dc.w $98A2, $A00,$F3F4  ; DATA XREF: ROM:off_59D62   o ROM:off_59DA2   o
word_ECCF8:     dc.w $9899, $A00,$F2F4  ; DATA XREF: ROM:off_59D62   o ROM:off_59DA2   o
word_ECCFE:     dc.w $9890, $A00,$F3F3  ; DATA XREF: ROM:off_59D62   o ROM:off_59DA2   o
word_ECD04:     dc.w $188F,    0,$FCEC  ; DATA XREF: ROM:off_59D62   o ROM:off_59DA2   o
                dc.w $9886, $A00,$F4F4
word_ECD10:     dc.w $987D, $A00,$F4F4  ; DATA XREF: ROM:off_59D62   o ROM:off_59DA2   o
word_ECD16:     dc.w $88D9, $900,$F7F3  ; DATA XREF: ROM:off_59DC2   o ROM:off_59DE2   o
word_ECD1C:     dc.w $98D3, $900,$F7F3  ; DATA XREF: ROM:off_59DC2   o ROM:off_59DE2   o
word_ECD22:     dc.w $98CA, $A00,$F5F3  ; DATA XREF: ROM:off_59DC2   o ROM:off_59DE2   o
word_ECD28:     dc.w $98C4, $600,$F5FA  ; DATA XREF: ROM:off_59DC2   o ROM:off_59DE2   o
word_ECD2E:     dc.w $98BE, $600,$F4F9  ; DATA XREF: ROM:off_59DC2   o ROM:off_59DE2   o
word_ECD34:     dc.w $90C4, $600,$F5F8  ; DATA XREF: ROM:off_59DC2   o ROM:off_59DE2   o
word_ECD3A:     dc.w $90CA, $A00,$F5F6  ; DATA XREF: ROM:off_59DC2   o ROM:off_59DE2   o
word_ECD40:     dc.w $90D3, $900,$F7F6  ; DATA XREF: ROM:off_59DC2   o ROM:off_59DE2   o
word_ECD46:     dc.w $8105, $D00,$F7EE  ; DATA XREF: ROM:off_59E02   o ROM:off_59E22   o
word_ECD4C:     dc.w  $101, $500,$F6FF  ; DATA XREF: ROM:off_59E02   o ROM:off_59E22   o
                dc.w $80FD, $500,$F9EF
word_ECD58:     dc.w   $F5, $700,$ED02  ; DATA XREF: ROM:off_59E02   o ROM:off_59E22   o
                dc.w $80EF, $600,$F5F2
word_ECD64:     dc.w   $E7, $500,$F0F9  ; DATA XREF: ROM:off_59E02   o ROM:off_59E22   o
                dc.w $80EB, $500,  $F6
word_ECD70:     dc.w $88DF, $700,$F1F8  ; DATA XREF: ROM:off_59E02   o ROM:off_59E22   o
word_ECD76:     dc.w  $8EB, $500,  $FA  ; DATA XREF: ROM:off_59E02   o ROM:off_59E22   o
                dc.w $88E7, $500,$F0F7
word_ECD82:     dc.w  $8F5, $700,$EDEE  ; DATA XREF: ROM:off_59E02   o ROM:off_59E22   o
                dc.w $88EF, $600,$F5FE
word_ECD8E:     dc.w  $901, $500,$F6F2  ; DATA XREF: ROM:off_59E02   o ROM:off_59E22   o
                dc.w $88FD, $500,$F902
word_ECD9A:     dc.w $891D, $500,$F8F8  ; DATA XREF: ROM:off_59E42   o ROM:off_59E62   o
word_ECDA0:     dc.w $8921, $500,$F8F8  ; DATA XREF: ROM:off_59E42   o ROM:off_59E62   o
word_ECDA6:     dc.w $8925, $500,$F8F8  ; DATA XREF: ROM:off_59E42   o ROM:off_59E62   o
word_ECDAC:     dc.w $8929, $500,$F9F8  ; DATA XREF: ROM:off_59E42   o ROM:off_59E62   o
word_ECDB2:     dc.w $910D, $500,$F8F9  ; DATA XREF: ROM:off_59E42   o ROM:off_59E62   o
word_ECDB8:     dc.w $9111, $500,$F8F9  ; DATA XREF: ROM:off_59E42   o ROM:off_59E62   o
word_ECDBE:     dc.w $9115, $500,$F9FA  ; DATA XREF: ROM:off_59E42   o ROM:off_59E62   o
word_ECDC4:     dc.w $9119, $500,$F9F9  ; DATA XREF: ROM:off_59E42   o ROM:off_59E62   o
word_ECDCA:     dc.w  $961, $100, $4EC  ; DATA XREF: sub_55518+10   o
                dc.w  $956, $200,$ECEC
                dc.w  $959, $D00, $4F4
                dc.w $894A, $E00,$ECF4
word_ECDE2:     dc.w $4800, $600,$E0F8  ; DATA XREF: ROM:stru_ECEAC   o
                dc.w $4806, $900,$F8F8
                dc.w $C80C, $600, $8F8
word_ECDF4:     dc.w $4824,    0,$1007  ; DATA XREF: ROM:stru_ECE90   o
                dc.w $4825, $C00,$18EF
                dc.w $481E, $600,  $F7
                dc.w $481C, $400,$FFF7
                dc.w $4818, $C00,$F7EF
                dc.w $C812, $600,$DFF7
word_ECE18:     dc.w $483C, $100,$10F2  ; DATA XREF: ROM:stru_ECE90   o
                dc.w $4834, $700,  $FA
                dc.w $4832, $400,$FBF6
                dc.w $C82A, $700,$DBF6
word_ECE30:     dc.w $4848, $700,  $FA  ; DATA XREF: ROM:stru_ECE90   o
                dc.w $4846, $400,$FBF6
                dc.w $C83E, $700,$DBF6
word_ECE42:     dc.w $4861, $C00,$18F1  ; DATA XREF: ROM:stru_ECE90   o
                dc.w $485B, $600,  $F9
                dc.w $4859, $400,  $F6
                dc.w $4856, $800,$F8F6
                dc.w $C850, $600,$E0F6
word_ECE60:     dc.w $4869, $800,$18F4  ; DATA XREF: ROM:stru_ECE90   o
                dc.w $4867, $400,$10F4
                dc.w $4865, $100,  $FC
                dc.w $4846, $400,$FBF6
                dc.w $C83E, $700,$DBF6
word_ECE7E:     dc.w $486C, $700,  $F8  ; DATA XREF: ROM:stru_ECE90   o
                dc.w $4832, $400,$FBF6
                dc.w $C82A, $700,$DBF6
stru_ECE90:     dc.w word_ECDF4-*       ; field_0 ; DATA XREF: update_ent_104+D4   o seven_force_0+7C   o ...
                dc.w     9              ; field_2
                dc.w word_ECE18-*       ; field_0
                dc.w     8              ; field_2
                dc.w word_ECE30-*       ; field_0
                dc.w     8              ; field_2
                dc.w word_ECE42-*       ; field_0
                dc.w     9              ; field_2
                dc.w word_ECE60-*       ; field_0
                dc.w     8              ; field_2
                dc.w word_ECE7E-*       ; field_0
                dc.w     8              ; field_2
                dc.w stru_ECE90-*       ; field_0
                dc.w     0              ; field_2
stru_ECEAC:     dc.w word_ECDE2-*       ; field_0 ; DATA XREF: update_ent_104+40   o update_ent_104+128   o ...
                dc.w $FF                ; field_2
                dc.w   $3A, $400, $FF0
                dc.w  $83A, $400, $F00
                dc.w   $32, $700,$EFF0
                dc.w $8832, $700,$EF00
                dc.w   $42, $800, $8EC
                dc.w  $842, $800, $8FC
                dc.w $883C, $900,$F8F4
                dc.w   $45, $900, $8EC
                dc.w  $845, $900, $8FC
                dc.w $883C, $900,$F8F4
                dc.w $8829, $A00,$F4F4
word_ECEF2:     dc.w  $842, $400,$1DF8  ; DATA XREF: ROM:off_32118   o
                dc.w  $83A, $700,$FDF8
                dc.w $882A, $F00,$DDF0
word_ECF04:     dc.w  $85C, $100,$F8DB  ; DATA XREF: ROM:off_316A6   o ROM:off_32118   o
                dc.w  $854, $D00,$F8E3
                dc.w $8844, $F00,$F003
word_ECF16:     dc.w  $874, $A00,$FBDD  ; DATA XREF: ROM:off_32118   o
                dc.w  $86E, $600,$F3F5
                dc.w $885E, $F00,$EB05
word_ECF28:     dc.w  $898, $400, $3FD  ; DATA XREF: ROM:off_32118   o
                dc.w  $896, $100,$F3F5
                dc.w  $88D, $A00, $3E5
                dc.w $887D, $F00,$E3FD
word_ECF40:     dc.w  $8AA, $A00, $BEE  ; DATA XREF: ROM:off_32118   o
                dc.w  $8B3, $900,$FBF6
                dc.w $889A, $F00,$DBF6
word_ECF52:     dc.w $88B9, $800,$FBF5  ; DATA XREF: ROM:off_322C8   o
word_ECF58:     dc.w $88BC, $900,$F6F5  ; DATA XREF: ROM:off_322C8   o
word_ECF5E:     dc.w $88C2, $A00,$F4F3  ; DATA XREF: ROM:off_322C8   o
word_ECF64:     dc.w $88CB, $600,$F4F7  ; DATA XREF: ROM:off_322C8   o
word_ECF6A:     dc.w $88D1, $200,$F3FC  ; DATA XREF: ROM:off_322C8   o
word_ECF70:     dc.w $88D4, $500,$F8F8  ; DATA XREF: ROM:off_316A6   o
word_ECF76:     dc.w $C84E, $F00,$F0F0  ; DATA XREF: ROM:stru_4E1E0   o ROM:stru_4F598   o
word_ECF7C:     dc.w $C85E, $F00,$EEF2  ; DATA XREF: ROM:stru_4F598   o
word_ECF82:     dc.w $C86E, $F00,$F0F0  ; DATA XREF: ROM:stru_4F598   o
word_ECF88:     dc.w $C87E, $F00,$EEEE  ; DATA XREF: ROM:stru_4F598   o
word_ECF8E:     dc.w $5800, $500,    8  ; DATA XREF: sub_4E060+4E   o ROM:stru_4F558   o
                dc.w $5804, $E00,  $E8
                dc.w $4804, $E00,$E8E8
                dc.w $C800, $500,$F008
word_ECFA6:     dc.w $4824, $200,$F10F  ; DATA XREF: ROM:stru_4F558   o
                dc.w $4820, $C00,$E9F7
                dc.w $C810, $F00,$F1EF
word_ECFB8:     dc.w $402B, $B00,$F8E8  ; DATA XREF: ROM:stru_4F558   o
                dc.w $4027, $500,$E8F0
                dc.w $4827, $500,$E800
                dc.w $C82B, $B00,$F800
word_ECFD0:     dc.w $484B, $200,$F1E9  ; DATA XREF: ROM:stru_4F558   o
                dc.w $4847, $C00,$E9E9
                dc.w $C837, $F00,$F1F1
word_ECFE2:     dc.w $C88E, $500,$F8F8  ; DATA XREF: ROM:stru_4E1E0   o
word_ECFE8:     dc.w $C892, $500,$F8F8  ; DATA XREF: ROM:stru_4E1E0   o
word_ECFEE:     dc.w $C896, $500,$F8F8  ; DATA XREF: ROM:stru_4E1E0   o
word_ECFF4:     dc.w $C89A,    0,$FCFC  ; DATA XREF: sub_4F0BA+18   o ROM:stru_4F15E   o
word_ECFFA:     dc.w $C89B, $500,$F8F8  ; DATA XREF: sub_4E060+124   o ROM:stru_4F15E   o
word_ED000:     dc.w $C89F, $A00,$F4F4  ; DATA XREF: ROM:stru_4F15E   o
word_ED006:     dc.w $C8A8, $F00,$F0F0  ; DATA XREF: ROM:stru_4F15E   o
word_ED00C:     dc.w $C8B8, $F00,$F0F0  ; DATA XREF: ROM:stru_4F15E   o
word_ED012:     dc.w $C8C8, $F00,$F0F0  ; DATA XREF: ROM:stru_4F15E   o
word_ED018:     dc.w $C8D8, $F00,$F0F0  ; DATA XREF: ROM:stru_4F15E   o
word_ED01E:     dc.w $C8E8, $F00,$F0F0  ; DATA XREF: ROM:stru_4F15E   o
word_ED024:     dc.w $6038, $500,$FA00  ; DATA XREF: ROM:stru_ED152   o ROM:stru_ED156   o
                dc.w $E838, $500,$FAF0
word_ED030:     dc.w $483C, $D00,$FBD0  ; DATA XREF: ROM:stru_ED13E   o
                dc.w $483C, $D00,$FBF0
                dc.w $483C, $D00,$FB10
                dc.w $6038, $500,$FA30
                dc.w $E838, $500,$FAC0
word_ED04E:     dc.w $583C, $D00,$F5D0  ; DATA XREF: ROM:stru_ED13E   o
                dc.w $583C, $D00,$F6F0
                dc.w $583C, $D00,$F510
                dc.w $6038, $500,$FA30
                dc.w $E838, $500,$FAC0
word_ED06C:     dc.w $403C, $D00,$FBD0  ; DATA XREF: ROM:stru_ED13E   o
                dc.w $403C, $D00,$FBF0
                dc.w $403C, $D00,$FB10
                dc.w $6038, $500,$FA30
                dc.w $E838, $500,$FAC0
word_ED08A:     dc.w $503C, $D00,$F6D0  ; DATA XREF: ROM:stru_ED13E   o
                dc.w $503C, $D00,$F7F0
                dc.w $503C, $D00,$F610
                dc.w $6038, $500,$FA30
                dc.w $E838, $500,$FAC0
word_ED0A8:     dc.w $6838, $500,$FAE4  ; DATA XREF: ROM:stru_ED156   o
                dc.w $6038, $500,$FA0C
                dc.w $C83C, $D00,$FAF0
word_ED0BA:     dc.w $6838, $500,$FADC  ; DATA XREF: ROM:stru_ED156   o
                dc.w $403C, $D00,$FAE6
                dc.w $6038, $500,$FA14
                dc.w $C83C, $D00,$FAFA
word_ED0D2:     dc.w $6838, $500,$FAD4  ; DATA XREF: ROM:stru_ED156   o
                dc.w $483C, $D00,$FAE0
                dc.w $6038, $500,$FA1C
                dc.w $C03C, $D00,$FA00
word_ED0EA:     dc.w $483C, $D00,$FAF0  ; DATA XREF: ROM:stru_ED156   o
                dc.w $6838, $500,$FACC
                dc.w $483C, $D00,$FAD7
                dc.w $6038, $500,$FA24
                dc.w $C03C, $D00,$FA09
word_ED108:     dc.w $583C, $D00,$F5F0  ; DATA XREF: ROM:stru_ED156   o
                dc.w $6838, $500,$FAC4
                dc.w $403C, $D00,$FAD0
                dc.w $6038, $500,$FA2C
                dc.w $C83C, $D00,$FA10
word_ED126:     dc.w $6838, $500,$FAEB  ; DATA XREF: ROM:stru_ED156   o
                dc.w $6038, $500,$FA05
                dc.w $C83C, $D00,$FAF0
                dc.w $E837,    0,$1FFF
stru_ED13E:     dc.w word_ED030-*       ; field_0 ; DATA XREF: sub_33E66+8   o ROM:stru_ED13E   o ...
                dc.w     1              ; field_2
                dc.w word_ED04E-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_ED08A-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_ED06C-*       ; field_0
                dc.w     1              ; field_2
                dc.w stru_ED13E-*       ; field_0
                dc.w     0              ; field_2
stru_ED152:     dc.w word_ED024-*       ; field_0 ; DATA XREF: sub_33D58+4   o
                dc.w $FF                ; field_2
stru_ED156:     dc.w word_ED024-*       ; field_0 ; DATA XREF: sub_33E32+6   o ROM:stru_ED156   o ...
                dc.w     1              ; field_2
                dc.w word_ED126-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_ED0A8-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_ED0BA-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_ED0D2-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_ED0EA-*       ; field_0
                dc.w     1              ; field_2
                dc.w word_ED108-*       ; field_0
                dc.w   $FF              ; field_2
word_ED172:     dc.w $480B, $100,$F8E9  ; DATA XREF: sub_4F956+94   o
                dc.w $4803, $D00,$F8F1
                dc.w $C800, $800,$F0F3
                dc.w $480D, $800,$EBF2
                dc.w $C810, $E00,$F3F2
word_ED190:     dc.w $4824, $400,$FBE1  ; DATA XREF: sub_4F956+AE   o ROM:off_50586   o
                dc.w $C81C, $D00,$F8F0
word_ED19C:     dc.w $482F, $500, $CEA  ; DATA XREF: ROM:off_50586   o
                dc.w $482C, $800, $4EC
                dc.w $C826, $900,$F4F4
word_ED1AE:     dc.w $483B, $100,$10FB  ; DATA XREF: ROM:off_50586   o
                dc.w $C833, $700,$F0F8
word_ED1BA:     dc.w $4846, $500, $C07  ; DATA XREF: ROM:off_50586   o
                dc.w $4843, $800, $4FD
                dc.w $C83D, $900,$F4F5
word_ED1CC:     dc.w $C84A, $E00,$F4F0  ; DATA XREF: ROM:000352A6   o
word_ED1D2:     dc.w $4859, $D00,$FAEE  ; DATA XREF: ROM:000352A6   o
                dc.w $C856, $800,$F2F6
word_ED1DE:     dc.w $C861, $A00,$F5F4  ; DATA XREF: ROM:000352A6   o
word_ED1E4:     dc.w $486D, $700,$F3F7  ; DATA XREF: ROM:000352A6   o
                dc.w $C86A, $200,$F307
word_ED1F0:     dc.w $C875, $B00,$F0F4  ; DATA XREF: ROM:000352A6   o
word_ED1F6:     dc.w $406A, $200,$F2F2  ; DATA XREF: ROM:000352A6   o
                dc.w $C06D, $700,$F2FA
word_ED202:     dc.w $C061, $A00,$F4F5  ; DATA XREF: ROM:000352A6   o
word_ED208:     dc.w $4056, $800,$F1F2  ; DATA XREF: ROM:000352A6   o
                dc.w $C059, $D00,$F9F2
word_ED214:     dc.w $4890, $500,$F9E7  ; DATA XREF: ROM:000352A6   o
                dc.w $4884, $E00,$F9F7
                dc.w $C881, $800,$F1F9
word_ED226:     dc.w $48A0, $800, $9F6  ; DATA XREF: ROM:000352A6   o
                dc.w $4894, $E00,$F1F6
                dc.w $C8A3, $500,$FEE6
word_ED238:     dc.w $48B9,    0, $DF4  ; DATA XREF: ROM:000352A6   o
                dc.w $48B7, $100, $5EC
                dc.w $C8A7, $F00,$EDF4
word_ED24A:     dc.w $48C9, $100, $AF9  ; DATA XREF: ROM:000352A6   o
                dc.w $48C6, $200,$FAF1
                dc.w $C8BA, $B00,$EAF9
word_ED25C:     dc.w $49C5, $500, $8F9  ; DATA XREF: ROM:000352A6   o
                dc.w $49C2, $200,$EEF1
                dc.w $C9B6, $B00,$E8F9
word_ED26E:     dc.w $48DA, $500, $9FD  ; DATA XREF: ROM:000352A6   o
                dc.w $48D7, $200,$F10A
                dc.w $C8CB, $B00,$E9F2
word_ED280:     dc.w $48EE, $800, $C00  ; DATA XREF: ROM:000352A6   o
                dc.w $48EA, $C00, $4F8
                dc.w $C8DE, $E00,$ECF0
word_ED292:     dc.w $48FD,    0, $803  ; DATA XREF: ROM:000352A6   o
                dc.w $48FE, $500,$FE0B
                dc.w $C8F1, $E00,$F0EB
word_ED2A4:     dc.w $490A, $100,$F9E9  ; DATA XREF: ROM:000352A6   o
                dc.w $C902, $D00,$F9F1
word_ED2B0:     dc.w $4910, $500,$FAF0  ; DATA XREF: ROM:000352A6   o
                dc.w $C90C, $500,$F600
word_ED2BC:     dc.w $491A, $500, $3F2  ; DATA XREF: ROM:000352A6   o
                dc.w $C914, $900,$F3F6
word_ED2C8:     dc.w $4922, $500, $1F7  ; DATA XREF: ROM:000352A6   o
                dc.w $C91E, $500,$F1FB
word_ED2D4:     dc.w $492E, $400, $FFA  ; DATA XREF: ROM:000352A6   o
                dc.w $C926, $700,$EFFA
word_ED2E0:     dc.w $4934, $500,  $FC  ; DATA XREF: ROM:000352A6   o
                dc.w $C930, $500,$F0F8
word_ED2EC:     dc.w $493E, $500,$FD05  ; DATA XREF: ROM:000352A6   o
                dc.w $C938, $600,$F1F5
word_ED2F8:     dc.w $4946, $500,$F802  ; DATA XREF: ROM:000352A6   o
                dc.w $C942, $500,$F4F2
word_ED304:     dc.w $C94A, $900,$F9EF  ; DATA XREF: sub_505D2+90   o
word_ED30A:     dc.w $C950, $600,$FBFB  ; DATA XREF: sub_505D2+96   o
word_ED310:     dc.w $4965,    0, $BF2  ; DATA XREF: sub_4FD76   o sub_4FE94+4CC   o
                dc.w $4966, $600,$FCE2
                dc.w $495A, $400,$EBF4
                dc.w $C95C, $A00,$F3F2
word_ED328:     dc.w $497B, $900, $DEC  ; DATA XREF: sub_4F956+E6   o sub_4FE94+4D8   o
                dc.w $496C, $800,$EDEC
                dc.w $C96F, $E00,$F5EC
word_ED33A:     dc.w $498F, $200,$E0E4  ; DATA XREF: sub_4F956+CE   o sub_4FE94:loc_5034E   o
                dc.w $4992, $D00,$F8EC
                dc.w $4981, $100,$E80C
                dc.w $C983, $E00,$E0EC
word_ED352:     dc.w $49B4, $400,$FADF  ; DATA XREF: sub_4FE94+4AA   o
                dc.w $49AC, $D00,$FAEF
                dc.w $499A, $E00,$E2EF
                dc.w $C9A6, $600,$E2DF
                dc.w     0, $700,$F0F0
                dc.w $8800, $700,$F000
                dc.w $8808, $300,$F0FC
                dc.w $880C, $300,$F0FC
word_ED382:     dc.w   $10, $B00,$ECE8  ; DATA XREF: sub_53318+1A   o
                dc.w $8810, $B00,$EC00
                dc.w $881C, $500,$F8F8
word_ED394:     dc.w $A820, $200,$F4FC  ; DATA XREF: sub_51C32+154   o sub_51C32+16C   o
word_ED39A:     dc.w $2837, $200, $8E8  ; DATA XREF: sub_51C32+14C   o sub_51C32+164   o
                dc.w $2833, $300,  $F0
                dc.w $A823, $700,$F0F8
                dc.w $284A, $500, $8F8
                dc.w $A83A, $F00,$E8F0
word_ED3B8:     dc.w $A84E, $200,$F3FC  ; DATA XREF: sub_51C32+100   o
word_ED3BE:     dc.w $A851, $100,$F8FC  ; DATA XREF: sub_51C32+114   o
word_ED3C4:     dc.w $2867,    0, $CEC
                dc.w $2868, $C00, $CF4
                dc.w $2863, $300,$ECEC
                dc.w $A853, $F00,$ECF4
word_ED3DC:     dc.w $386C, $D00,  $F0
                dc.w $A86C, $D00,$F0F0
word_ED3E8:     dc.w $A874, $A00,$F4F4
                dc.w $A87D, $500,$F8F8
word_ED3F4:     dc.w $3889, $D00,  $E0  ; DATA XREF: ROM:off_528C8   o
                dc.w $3881, $D00,    0
                dc.w $2889, $D00,$F0E0
                dc.w $A881, $D00,$F000
word_ED40C:     dc.w $28A4, $F00,$FCE4  ; DATA XREF: ROM:off_528C8   o
                dc.w $289E, $900,$FC04
                dc.w $289D,    0,$F4F4
                dc.w $A891, $E00,$E4FC
word_ED424:     dc.w $20BC, $700,  $F0  ; DATA XREF: ROM:off_528C8   o
                dc.w $20B4, $700,$E0F0
                dc.w $28BC, $700,    0
                dc.w $A8B4, $700,$E000
word_ED43C:     dc.w $20A4, $F00,$FCFC  ; DATA XREF: ROM:off_528C8   o
                dc.w $209E, $900,$FCE4
                dc.w $209D,    0,$F404
                dc.w $A091, $E00,$E4E4
                dc.w $A8C4, $800,$FCF4
                dc.w $28C9, $500,$FAF2
                dc.w $A8C7, $100,$F202
                dc.w $A8CD, $200,$F4FD
                dc.w $20C9, $500,$F9FF
                dc.w $A0C7, $100,$F1F7
word_ED478:     dc.w $A82B, $700,$F0F8  ; DATA XREF: sub_51C32+144   o sub_51C32+15C   o
word_ED47E:     dc.w  $80C, $300,$70FC  ; DATA XREF: sub_53318+60   o update_ent_11D+3C   o
                dc.w  $808, $300,$50FC
                dc.w  $808, $300,$30FC
                dc.w  $808, $300,$10FC
                dc.w  $808, $300,$F0FC
                dc.w  $808, $300,$D0FC
                dc.w  $808, $300,$B0FC
                dc.w     0, $700,$90F0
                dc.w $8800, $700,$9000
